### ISSUE TITLE
La fonction de citation ne conserve pas les sauts de ligne

### ISSUE THREAD

**Issue by Exagone313** [NextINpact/nextinpactv7#10]
Les sauts de lignes sont manquants dans la copie du commentaire cité.

**Comment by papci** [comment]
Fixed

**Comment by Exagone313** [comment]
Ce n'est pas encore complètement corrigé, ou le comportement des sauts de ligne a peut-être été modifié (#13).

Un message :
```
test
test2

test 3
```

Une fois cité devient :
```
> (quote:325205:Exagone313)
>test test2
>
>test 3
```
