### ISSUE TITLE
#LeBrief - Article de l'an 1

### ISSUE THREAD

**Issue by Otiel** [NextINpact/nextinpactv7#100]
Un exemple d'article daté du 1er janvier 0001:

https://www.nextinpact.com/lebrief/43359/13134-la-securite-chez-doctolib-----on-passait-notre-temps-a-serrer-les-fesses----de---fausses-accusations---pour-la-plateforme

![image](https://user-images.githubusercontent.com/3851902/91979272-cef5a780-ed25-11ea-9696-741506e58cae.png)

**Comment by papci** [comment]
Corrigé
