### ISSUE TITLE
Masquer la Une : le contenu se déplace après le début de la lecture

### ISSUE THREAD

**Issue by dominiquefournier** [NextINpact/nextinpactv7#101]
Lorsque l'on est abonné, la préférence "Masquer la une" est appliquée après que le contenu soit affiché et lisible.
Du coup, on commence à lire les titres en attendant la fin de chargement de la page. A la fin, la une se cache, et hop, la page remonte pour supprimer la une (car j'ai choisi "masquer la une" dans mes préférences). Il faut alors tout relire...
Il serait mieux d'intégrer directement les préférences dès la construction de la page et de ne pas afficher la une du tout !

**Comment by papci** [comment]
Bonjour,

Sur quel configuration ? nous ne reproduisons pas de notre coté.

**Comment by dominiquefournier** [comment]
Firefox 62.12esr Linux Debian, en écran large. En écran taille téléphone, le problème n'apparait pas. Je vous mets une vidéo en pièce jointe (Zippé car Github ne veut pas de Webm). On voit bien que je suis considéré comme non connecté pendant 2s avant que la connexion soit faite et que les préférences s'appliquent.
[cinnamon-20200909-2.webm.zip](https://github.com/NextINpact/nextinpactv7/files/5194810/cinnamon-20200909-2.webm.zip)

Merci

**Comment by papci** [comment]
Comme indiqué sur la page d'accueil de ce dépot (https://github.com/NextINpact/nextinpactv7), nous ne prenons pas en charge les anciennes versions de Firefox pour des raisons de sécurité et de support des technologies que nous utilisons.
