### ISSUE TITLE
Bug d'affichage des émojis

### ISSUE THREAD

**Issue by ecatomb** [NextINpact/nextinpactv7#103]
Bonjour,

Les émojis s'affiche mal sous macOS (Safari et Edgium). Exemple de la page suivante :
https://www.nextinpact.com/lebrief/43412/lebrief-est-retour#comment/1822409

Si je charge la page : les émojis ne s'affichent pas (il y a le texte à la place :nonnon: , :D , etc...)
Par contre, si je clique sur le numéro d'un poste, la page se recharge et là les émojis sont bien affichés.
Mais si je recharge ensuite la page... ils disparaissent de nouveau.

**Comment by ecatomb** [comment]
A priori, cela ne le fait que pour les articles lebrief et pas les autres

**Comment by papci** [comment]
Fixed ;)
