### ISSUE TITLE
Le flux RSS envoie vers une erreur 404

### ISSUE THREAD

**Issue by gandf** [NextINpact/nextinpactv7#105]
Depuis aujourd'hui le flux RSS de nextinpact renvoie vers une page 404. Le flux Inpact-hardware fonctionne toujours.
J'ai récupéré de nouveau l'url mais rien ne change. L'url est de la forme suivante :
https://www.nextinpact.com/rss-complet/xxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Le message d'erreur est 404 en gros puis :

> OUPS !!! La page que vous avez demandée est malheureusement introuvable.
> La page que vous recherchez a peut-être été renommée, déplacée ou effacée.

Il y a aussi John Travolta qui semble égaré sur cette page.

**Comment by ecatomb** [comment]
Cela semble (re)marcher

**Comment by gandf** [comment]
Exact.

**Comment by Exagone313** [comment]
Ça semble être causé par le service worker.
