### ISSUE TITLE
Les liens vers l'édition précédente/suivante du Brief n'en sont pas

### ISSUE THREAD

**Issue by trou** [NextINpact/nextinpactv7#106]
Avec vimium, sur firefox, le lien "< Édition du 2 septembre 2020" n'est pas reconnu comme tel et donc ne peut pas être "cliqué" sans effectivement utiliser la souris. Il manque une balise `<a>` ou un attribut "bouton" je pense.

**Comment by ecatomb** [comment]
Pas de problème chez moi, sur quelle page as-tu ce bug ?

**Comment by trou** [comment]
https://www.nextinpact.com/lebrief/620 celle là par exemple. avec firefox 80,  thème "sombre", affichage "normal"

**Comment by ecatomb** [comment]
Merci pour la précision. Je n'utilise pas vimium, c'est pour ça.
Ton exemple de page sera sûrement utile pour l'équipe afin de bien comprendre le bug.

**Comment by trou** [comment]
Corrigé :)

**Comment by papci** [comment]
Merci à toi d'avoir remonté le souci ;)
