### ISSUE TITLE
Citation du "répondre" qui reste affiché

### ISSUE THREAD

**Issue by ecatomb** [NextINpact/nextinpactv7#107]
Bonjour,

Dans les commentaire, les réponses à un commentaire d'un utilisateur sont précédées de son nom (cf 1 dans la capture)
Si on place la souris sur ce nom, le commentaire s'affiche. Si on clique ensuite, cela affiche la page contenant ce commentaire en se calant dessus.
Mais ce commentaire reste souvent affiché (surtout quand on change de page de commentaire). Donc cela faire un résultat bizarre comme sur cette capture.

La citation à côté du 2 dans la capture correspond à celle affichée sur la page 2 des commentaires alors qu'on est maintenant sur la page 1.

J'espère avoir été assez clair. Bonne journée.

![Capture d’écran 2020-09-06 à 19 16 34](https://user-images.githubusercontent.com/69631254/92331441-e959b900-f076-11ea-929a-ba9e71c3de1c.jpg)

**Comment by BenjaminINpact** [comment]
Merci pour tes retours Ecatomb, ce problème est fixed.

**Comment by ghost** [comment]
Problème toujours là...

<img width="862" alt="Capture d’écran 2020-10-05 à 13 41 34" src="https://user-images.githubusercontent.com/69631254/95075488-88beaa00-0710-11eb-80f7-6f5b4d5b711a.png">
