### ISSUE TITLE
#LeBrief - Certains articles sont illisibles

### ISSUE THREAD

**Issue by bixou** [NextINpact/nextinpactv7#108]
- Type : Bug UI/UX
- Appareil : iPhone 6S
- OS : iOS 13.7 - Aucune modification de faite sur la taille du texte dans les réglages d'iOS.

Certains articles du Brief sont illisibles sur mon appareil. Cela ne se produit pas dans la vue "Liste des Articles", uniquement en vue "1 Article". 
Exemple avec 2 articles du Vendredi 4 Septembre, celui sur le [Nintendo Direct des 35 ans de Mario](https://www.nextinpact.com/lebrief/43546/nintendo-direct-30-ans-super-mario-game-watch-mario-kart-live-3d-world-bowsers-fury) et celui sur [la nouvelle interface Xbox](https://www.nextinpact.com/lebrief/43540/xbox-series-x-microsoft-presente-sa-nouvelle-interface)

![IMG_2236](https://user-images.githubusercontent.com/4839646/92366794-e3ef8380-f0f5-11ea-8742-c463f90754ce.PNG)
![IMG_2237](https://user-images.githubusercontent.com/4839646/92366818-ebaf2800-f0f5-11ea-8c21-30d0e15655bb.PNG)

**Comment by papci** [comment]
Fixed ;)
