### ISSUE TITLE
V7 avec KeepassXC et Firefox

### ISSUE THREAD

**Issue by fgouland** [NextINpact/nextinpactv7#109]
avec Nxi V7, à la mise en place, je pouvais entrer mes identifiants par l'intermédiaire de KeepassXc et son interface Firefox (Win10Pro 2004). Depuis quelques jours, ce n'est plus possible et je dois de nouveau entrer mes identifiants à la main 😥 . Vous avez changé un truc à moins que ce ne soit dans la chaine Win10, Firefox, keepassXC et son module FF...

Merci d'avance et bon courage

**Comment by papci** [comment]
Bonjour, 

Nous n'avons rien changé de notre coté.
