### ISSUE TITLE
Zoom sur les photos/images

### ISSUE THREAD

**Issue by HPact** [NextINpact/nextinpactv7#110]
Bonjour,
Lorsqu'on est sur un écran 4k, l'affichage des photos/images, notamment celles avec du texte (cf. l'article sur Western Digital et les vitesses de rotation) sont difficilement lisibles.
J'ai tenté le clic dessus, mais ça ne fait rien. Il me semblait qu'à une époque cela fonctionnait...

Merci d'avance

**Comment by bastien-c** [comment]
merci pour ton retour, il est maintenant possible d'ouvrir les images en taille réelle au clic.
