### ISSUE TITLE
Liens incorrects pour Le Brief dans le flux RSS complet

### ISSUE THREAD

**Issue by Exagone313** [NextINpact/nextinpactv7#112]
Dans le flux RSS complet, les liens vers Le Brief sont de la forme `https://www.nextinpact.com/article/<id>/<titre>` :  
https://www.nextinpact.com/article/43611/rgpd-classement-forbes-sanctionne-par-cnil-hongroise

Ce lien est incorrect et renvoie vers l'accueil du site. Il faut remplacer `article` par `lebrief`.

Dans le flux RSS public il est bien de la forme `https://www.nextinpact.com/lebrief/<id>/<titre>` :  
https://www.nextinpact.com/lebrief/43611/rgpd-classement-forbes-sanctionne-par-cnil-hongroise

**Comment by Exagone313** [comment]
PS : En plus de corriger les liens dans le flux RSS complet, il pourrait être envisageable de rediriger les liens du brief incorrects.

**Comment by papci** [comment]
Fixed
