### ISSUE TITLE
Articles cachés 

### ISSUE THREAD

**Issue by ecatomb** [NextINpact/nextinpactv7#113]
Bonjour,

Je ne vois aucun articles de la journée via la page d’accueil ... Ils sont par contre accessibles via la recherche.

Merci

![DF138EAE-40AD-4A00-B11A-CED57A9F2F43](https://user-images.githubusercontent.com/69631254/92594189-bac02600-f2a2-11ea-84ca-1b0affa87b97.png)
![75D34039-136B-4F5E-82B4-7BD6966D8FB4](https://user-images.githubusercontent.com/69631254/92594195-bbf15300-f2a2-11ea-8ce3-f76072254980.png)

**Comment by papci** [comment]
C'est corrigé.

**Comment by ecatomb** [comment]
Merci, je les vois de nouveau 👍
