### ISSUE TITLE
Couleurs du texte dans les champs du formulaire de contact quand on a un navigateur avec thème sombre

### ISSUE THREAD

**Issue by ldidry** [NextINpact/nextinpactv7#114]
Quand on a un navigateur avec un thème sombre, les champs ont un fond¹ foncé et le texte en blanc.

Le formulaire de contact force la couleur de fond des champs en blanc, mais la couleur du texte n’est pas forcée, ce qui me fait du blanc sur blanc, donc c’est illisible ¯\_(ツ)_/¯

¹ background-color, quoi

**Comment by BenjaminINpact** [comment]
Bonjour,
Il semblerait que ce soit un problème d'environnement, quel navigateur avec quel thème utilisez-vous ?

**Comment by ldidry** [comment]
Firefox avec le thème sombre natif, KDE avec thème breeze dark et NextInpact avec le thème sombre.

Il est possible que ça vienne du cumul thème sombre KDE + FF, mais de toute façon, le souci vient du fait que le `background-color` soit défini sur le champ, sans que `color` ne soit défini : il faut définir les deux car on ne peut connaître les réglages des gens :wink: 

Je vous rassure, c’est un petit bug qui se retrouve un peu partout sur le net :slightly_smiling_face:

**Comment by ecatomb** [comment]
Pas de problème avec Safari, c'est bien du texte noir sur fond blanc que j'ai avec les 4 thèmes sombres.
Bon, c'est un peu clair comme fond mais pas gênant 😅

**Comment by bastien-c** [comment]
c'est corrigé :)

**Comment by ldidry** [comment]
Super, merci ! :+1:
