### ISSUE TITLE
Retirer la betaV7 sur la gestion du compte

### ISSUE THREAD

**Issue by GourouLubrik** [NextINpact/nextinpactv7#115]
Il faudrait maintenant retirer la portion dédié à la beta de la v7 sur la gestion du compte https://compte.nextinpact.com/gestion-util pour les abonnés.
Surtout que le lien vers la beta pointe maintenant vers une erreur 404

![image](https://user-images.githubusercontent.com/7873918/92910763-a9088b00-f428-11ea-9668-cb5cef432cea.png)

:kissing_heart:

**Comment by papci** [comment]
fixed ;)
