### ISSUE TITLE
Rubrique dessin de flock

### ISSUE THREAD

**Issue by ecatomb** [NextINpact/nextinpactv7#118]
Plusieurs bugs (test sous iOS)
• en horizontal l’image est petite... et je n’ai pas trouvé comment l’agrandir
• l’icône pour passer à l’image suivante est un peu masqué sur l’image des boxeurs
• les icônes des images du bas ne défilent pas à la bonne vitesse
• les smileys ne s’affichent pas

![E9B79DE1-EA1E-4CE7-900E-48EE09136457](https://user-images.githubusercontent.com/69631254/92996244-86e73980-f50a-11ea-8748-313763a2dad1.png)
![5A857B61-AB94-4ED9-A9EB-85F760D2AC75](https://user-images.githubusercontent.com/69631254/92996245-89499380-f50a-11ea-8c23-e0f0d8988432.png)
![1FE737F1-DC56-4C06-A4B4-0332B7764F7D](https://user-images.githubusercontent.com/69631254/92996250-8babed80-f50a-11ea-9fbd-16d914a3e3e7.png)
![74C07462-EF93-4472-B9D1-DE2DF40C4953](https://user-images.githubusercontent.com/69631254/92996251-8cdd1a80-f50a-11ea-8b49-d18fcd886dd8.png)

**Comment by Telev78** [comment]
De manière générale, sur PC également les images sont trop petites.

**Comment by sylvercis** [comment]
Sous Firefox sur PC avec une résolution classique de 1920*1080, les dessins sont réduits inutilement:

![image](https://user-images.githubusercontent.com/34790318/93734745-cda7f400-fbda-11ea-8b2c-5b8d8d088fa1.png)

j'ai modifié le css comme cela pour corriger mon problème:
`.__slick-main img {
	max-height: none !important;
}`

![image](https://user-images.githubusercontent.com/34790318/93735012-bddcdf80-fbdb-11ea-98ba-4129e0bdc948.png)

**Comment by pehadavid** [comment]
C'est corrigé ;)
