### ISSUE TITLE
Lien vers les commentaires

### ISSUE THREAD

**Issue by ecatomb** [NextINpact/nextinpactv7#119]
Bonjour,

Le lien vers les commentaires est par défaut # si on n'en a pas encore vu.
Exemple : https://www.nextinpact.com/article/43399/dropbox-passwords-vault-backup-notre-prise-en-mains-nouveautes#

Ensuite, s'il y a des commentaires non lu ou pas, cela affiche bien un lien vers le dernier commentaire.

Un moyen d'accéder aux commentaires d'un article sans avoir à scroller vers le bas (alors qu'on l'a déjà lu) ?

**Comment by BenjaminINpact** [comment]
Le bon comportement est au rdv ;)

**Comment by ghost** [comment]
Ah ? Dans lebrief ou un article, si je n'ai pas vu les commentaires, le lien vers les commentaire est par exemple :
https://www.nextinpact.com/lebrief/44058/etats-unis-rapport-parlementaire-radical-sur-gafa-et-leurs-pouvoirs#
https://www.nextinpact.com/article/43884/ubuntu-20-10-beta-paradoxe-dune-distribution-a-fois-moderne-et-statique#

Ben cela affiche le début de la page. Safari 14 sur macOS Catalina 10.15.7 ignore le # dans ce cas là et le supprime d'ailleurs dans l'adresse de la page.
