### ISSUE TITLE
Le champ "Editer" ne suit pas le theme

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/nextinpactv7#12]
J'ai choisit un thème sombre, mais quand on clic sur éditer, on se retrouve avec un truc très éblouissant : 
![image](https://user-images.githubusercontent.com/2286246/88212915-4d0b5c80-cc58-11ea-9547-421d83b1dbbd.png)

Le champ "Signaler" est de la bonne couleur.

**Comment by papci** [comment]
Fixed ;)

**Comment by Cqoicebordel** [comment]
Confirmed fixed :)
