### ISSUE TITLE
Désabonnement impossible (abo récurrent)

### ISSUE THREAD

**Issue by jilucorg** [NextINpact/nextinpactv7#120]
La page de gestion de mon abonnement (https://compte.nextinpact.com/gestion-util) ne donne pas de possibilité de me désabonner  ↓
![Sélection_004](https://user-images.githubusercontent.com/71324568/93203657-141dce80-f755-11ea-8520-6c9bd731d1ff.jpg)

Et le bouton ![Sélection_005](https://user-images.githubusercontent.com/71324568/93204133-e08f7400-f755-11ea-826a-19b9d9f0c44d.jpg) du formulaire de contact − pour m'adresser au service abonnements − reste sans effet...

[Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0 (blockeur de pub désactivé)]

**Comment by papci** [comment]
Bonjour,

Il vaut mieux contacter le support (support@nextinpact.com) dans ce cas là.

**Comment by jilucorg** [comment]
OK merci je vais le faire, mais bon c'est ecatomb sur le forum qui m'a conseillé d'ouvrir un ticket, donc visiblement puisque c'est 'closed' c'est que ce qui m'arrive n'est donc pas deux bugs... ;)

**Comment by ecatomb** [comment]
Voir son poste ici :
https://forum.nextinpact.com/topic/175055-comment-se-désabonner-de-nextinpact/?tab=comments#comment-2915011

Ce serait bien de trouver l'origine du problème vu qu'ils sont plusieurs dans le même cas. Il faudrait au moins résoudre le problème du formulaire de contact (de mon côté il fonctionne bien).
