### ISSUE TITLE
Smiley :dix:

### ISSUE THREAD

**Issue by ecatomb** [NextINpact/nextinpactv7#121]
Dans les commentaires du site, ce smiley ne s'affiche pas correctement.
:dix: affiche le 😁 du site suivi de ix:

Exemple :
https://www.nextinpact.com/lebrief/43730/lutte-contre-haine-en-ligne-personnalites-freezent-leurs-comptes-facebook-et-instagram#comment/1824708

**Comment by papci** [comment]
Fixed
