### ISSUE TITLE
Ajouter une séparation journalière des articles sur la page d'accueil

### ISSUE THREAD

**Issue by Nozalys** [NextINpact/nextinpactv7#122]
Proposition d'amélioration :
NXIv6 séparait les articles de chaque jour avec un séparateur indiquant le nom du jour de parution "jeudi 17 octobre". Cela manque à la v7, ce qui rend le repérage pendant le scrolling presque impossible. Seule la date en petit permet de se repérer.
C'est fait dans l'encart #LeBrief, il serait bon de faire de même, avec le même style dans la colonne principale.

**Comment by papci** [comment]
Bonjour,

La séparation par date ne reviendra pas. Pour ceux qui souhaitent une alternative, des INpactiens ont développé un script : 
https://forum.nextinpact.com/topic/175086-userscript-pour-mettre-en-valeur-les-news-du-jour-nxi-v7/
