### ISSUE TITLE
Texte d'édition superposé au reste du texte...

### ISSUE THREAD

**Issue by ecatomb** [NextINpact/nextinpactv7#124]
Bonjour,

Je n'ai ce bug que sur cette page (iOS14 et Safari) :
https://www.nextinpact.com/article/43761/evolution-exposition-aux-ondes-avec-arrivee-5g-anfr-fait-point

Le "Édité par refuznik le 18/09/2020 à 18:35" ne semble pas fixé au post associé et se superpose au reste
![IMG_3905](https://user-images.githubusercontent.com/69631254/93667527-e3a4a000-fa86-11ea-882b-7141e383ca09.jpeg)
![IMG_3906](https://user-images.githubusercontent.com/69631254/93667528-e43d3680-fa86-11ea-823f-8b650d037b5c.jpeg)

**Comment by ecatomb** [comment]
Je viens de voir pareil sur une autre page (avec macOS Catalina et Safari 14)
https://www.nextinpact.com/lebrief/43693/chrome-os-google-travaille-a-separer-navigateur-systeme#/page/2

Dans les deux cas, le commentaire est une réponse à une autre personne (le nom est tout au début du commentaire) éditée.

<img width="446" alt="Capture d’écran 2020-09-19 à 15 58 32" src="https://user-images.githubusercontent.com/69631254/93669008-1784c300-fa91-11ea-9f5e-b267a1a505c4.png">

**Comment by bastien-c** [comment]
c'est corrigé, merci pour le signalement
