### ISSUE TITLE
Smiley clignotant 😅

### ISSUE THREAD

**Issue by ecatomb** [NextINpact/nextinpactv7#125]
Bonjour,

Dans les commentaires, certain smiley affiché ont un bug : ils sont alternativement sur fond blanc puis transparent. Exemple sur cette page avec iOS 14 et Safari :
https://www.nextinpact.com/article/43761/evolution-exposition-aux-ondes-avec-arrivee-5g-anfr-fait-point

Capture avec fond blanc :
![IMG_3907](https://user-images.githubusercontent.com/69631254/93667627-bb697100-fa87-11ea-8ff9-6026db117ce7.jpeg)

En vidéo :
[RPReplay_Final1600511481.mov.zip](https://github.com/NextINpact/nextinpactv7/files/5249862/RPReplay_Final1600511481.mov.zip)

**Comment by bastien-c** [comment]
Nous ne parvenons pas à reproduire ce comportement de notre côté. 
Avez-vous de nouveau rencontré ce problème ?

**Comment by ghost** [comment]
Quand les smiley s'afficheront de nouveau, je ferais un test 😛
Depuis plusieurs jours, c'est du texte à la place comme :mdr:
cf un autre ticket

**Comment by ghost** [comment]
Les smileys refonctionnent, j'ai donc pu vérifier et tout est rentré dans l'ordre.
On peut clôturer ce ticket 😉
