### ISSUE TITLE
Partie vide dans un commentaire

### ISSUE THREAD

**Issue by ecatomb** [NextINpact/nextinpactv7#126]
Bonjour,

Avec macOS Catalina et Safari 14 j'ai une partie vide dans un commentaire de cette actualité. Pas de souci avec Edge chromium
https://www.nextinpact.com/lebrief/43745/publicite-adressee-a-tv-bouygues-telecom-signe-avec-google-ad-manager

<img width="836" alt="Capture d’écran 2020-09-19 à 16 26 37" src="https://user-images.githubusercontent.com/69631254/93669549-3a18db00-fa95-11ea-9d2b-3aba181b1b66.png">

**Comment by DuchkPy** [comment]
J'ai aussi ce soucis d'affichage sous Windows 10 avec les 2 navigateurs :
* Firefox
  * Firefox 80.0
  * User Agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0
* Edge
  * Chrome 85.0.4183.102
  * User Agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51

**Comment by BenjaminINpact** [comment]
Ce problème fait partie du passé maintenant :)
