### ISSUE TITLE
Carrousel d'images

### ISSUE THREAD

**Issue by guiest63** [NextINpact/nextinpactv7#127]
Testé sous Android 10, chrome 85 et Firefox 80
Petit bug d'affichage des carrousel d'image sous Android : les images sont systématiquement rognées sur la droite : 
(tests sur la page de Floxk et sur l'article sur les nouveautés d'iOS 14)
![carousel_android10_oneplusnord_chrome85](https://user-images.githubusercontent.com/71634205/93748139-086c5500-fbf8-11ea-8f8a-1610c08ef227.jpg)
![flock_android10_oneplusnord_chrome85](https://user-images.githubusercontent.com/71634205/93748141-099d8200-fbf8-11ea-858a-b2bf185344ab.jpg)

**Comment by ecatomb** [comment]
C'est peut-être aussi lié à la taille de ton écran ?

**Comment by guiest63** [comment]
C'est possible, en paysage ça ne le faisait pas...
Faisait parce que depuis la mise à jour d'aujourd'hui, qui a modifié la taille d'affichage des images, le souci est corrigé !

**Comment by papci** [comment]
Effectivement, c'est corrigé ;)
