### ISSUE TITLE
Affichage aléatoire des émoticônes "historiques"

### ISSUE THREAD

**Issue by guiest63** [NextINpact/nextinpactv7#128]
Les émoticônes historiques s'affichent aléatoirement sous Chrome 85/Firefox80 Android 10 (Oneplus Nord) : souvent, seuls les codes s'affichent. Recharger la page permet de les afficher correctement de temps en temps (et au final c'est souvent inefficace). Même après suppression du cache
![emoticones_codes](https://user-images.githubusercontent.com/71634205/93748655-e6bf9d80-fbf8-11ea-9c89-7d87ad7c8899.jpg)

**Comment by papci** [comment]
Bonjour,

On ne reproduit pas de notre coté. Merci de poster un rapport complet comme indiqué sur la page d'accueil  ;)

**Comment by guiest63** [comment]
En fait, depuis la mise à jour d'hier, le souci n'apparaît plus... Tant mieux ! :)
