### ISSUE TITLE
[Nouvelle fonctionnalité] Traiter "entrer" comme une vraie nouvelle ligne

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/nextinpactv7#13]
Le champs commentaire utilise Markdown pour gérer le formatage, ce qui est très bien.  
Mais il m'est arrivé de nombreuses fois d'avoir à éditer un commentaire parce que j'ai oublié de mettre le double espace à la fin d'une ligne.

Ce que je propose ici, c'est que presser la touche "entrer" ajoute automatiquement ces deux espace, et que shift+entrer garde le fonctionnement actuel, c'est à dire de ne pas mettre d'espace.

J'ai conscience que cela pourrait importuner ceux qui ont l'habitude. Ce n'est pas certain cependant. Mais dans tous les cas, ça pourrait être derrière une option.

**Comment by papci** [comment]
Hello,

Merci pour la suggestion, mais cela serait trop perturbant pour ceux qui ignorent le comportement du MD.

**Comment by Cqoicebordel** [comment]
Euh, au contraire. Pour ceux qui ne savent pas que c'est du MD, pour eux, taper "entrer" ferait apparaître une nouvelle ligne dans leur commentaire. Exactement ce qu'ils espéraient voir apparaître en pressant "entrer".  
C'est le comportement actuel (ne pas faire de nouvelle ligne après avoir pressé "entrer") qui est déroutant pour ceux qui ne savent pas que c'est du MD.
