### ISSUE TITLE
Email d'article offert non reçu

### ISSUE THREAD

**Issue by Mackelsj** [NextINpact/nextinpactv7#131]
3 tentatives de partage de l'article suivant et aucun email reçu
https://www.nextinpact.com/article/43440/quand-deux-trous-noirs-interdits-fusionnent-pour-donner-naissance-trou-noir-inedit

2 x sur le même email yahoo.fr, 1x sur un email pro
Aucun email reçu, y compris dans les spams

**Comment by Passific** [comment]
J'ai le même problème avec une adresse gmail aujoud'hui...
Ni reçu, ni dans les spams.

**Comment by pehadavid** [comment]
Bonjour,

Pour ce genre de problème il vaut mieux contacter sur le support : https://www.nextinpact.com/contact
