### ISSUE TITLE
Mauvais formatage d'un commentaire

### ISSUE THREAD

**Issue by bansan85** [NextINpact/nextinpactv7#132]
https://www.nextinpact.com/article/43838/net-5-0-en-release-candidate-erreurs-et-futur-dun-framework-unifie#comment/1826149

![image](https://user-images.githubusercontent.com/9248729/94453358-ddae6d80-01b0-11eb-9a6d-cfb19ce76e17.png)

"tiret" n'est pas correctement aligné verticalement alors que dans le commentaire suivant, "Cacao" l'est bien.

Un lien avec l'issue #126 ?

Google Chrome Version 85.0.4183.121 (Build officiel) (64 bits)

**Comment by bansan85** [comment]
@papci : problème corrigé ? Je ne trouve pas d'autres commentaires qui posent problèmes (alors qu'il y a 10 jours, j'en avais trouvé un ou deux autres). Par contre, le commentaire de référence pour ce bug a changé.

**Comment by BenjaminINpact** [comment]
Hello, yes c'est fix de ce coté là.

**Comment by bansan85** [comment]
@BenjaminINpact 
C'est de retour...

https://www.nextinpact.com/article/44374/copie-privee-en-2019-270-millions-deuros-collectes-et-tres-peu-rembourses-aux-pros#comment/1833459

![image](https://user-images.githubusercontent.com/9248729/97467408-749f4e80-1944-11eb-9c76-31844202d9b1.png)

Vu avec les dernières versions de Chrome et Firefox.
