### ISSUE TITLE
Impossible de se connecter à son compte

### ISSUE THREAD

**Issue by dareg** [NextINpact/nextinpactv7#133]
Lorsque je clique sur l'engrenage ou "connexion", le menu de connexion ne s'affiche pas.
Idem si je clique sur le menu hamburger de gauche, rien ne se passe.

Testé avec Firefox 68.12.0esr (toutes extensions désactivées), sur Debian 10.6

**Comment by papci** [comment]
Bonjour,

Comme indiqué à l'accueil de ce dépôt, nous ne supportons pas le navigateur mentionné pour des raisons de sécurité.

# Navigateurs Supportés

* Les deux dernières versions de l'ensemble des navigateurs basés sur Chromium (Chrome, Edge, Opera, Vivaldi etc.)
* Les deux dernières version de Firefox
* La dernière version de Firefox ESR
* Les deux dernières version de Safari (Mac et iOs)

**Comment by dareg** [comment]
Ah ouais j'avais pas vu qu'une nouvelle version de Firefox ESR était sorti.
Mais bon, je trouve un peu dommage que le site ne fonctionne plus sur un navigateur sorti il y a un mois.
