### ISSUE TITLE
le bandeau NXI ne fonctionne plus

### ISSUE THREAD

**Issue by Jaguar-** [NextINpact/nextinpactv7#134]
Bonjour,

sur le PC du boulot, le bandeau NXI ne s'ouvre plus sous Firefox, impossible de se logger
Sur le chat je vois que je ne suis pas le seul (AltreX, Gilbert_Gosseyn)
Je suis sous FF 68.12.0esr (64 bits) (même chose avec modules désactivés)

Par contre celà marche sous Chrome
Et Inpact Hardware fonctionne bien sous FF

Jaguar_fr

**Comment by agrimpard** [comment]
Bonjour, je confirme, même version ESR de Firefox.
Une erreur sur la console :
`14:16:22,908 SyntaxError: invalid regular expression flag s main-es2015.75737dd38cfe3f6e0a57.js:1:2206695`
Je pense que ça bloque tout votre JS.
Ce serait peut-être pas mal de prévoir un fallback sans JS sur votre navigation, particulièrement le login ...

**Comment by dareg** [comment]
J'ai le même problème. Voir #133

**Comment by agrimpard** [comment]
D'accord, ESR est passé en 78 donc plus de gestion de la 68.
Pour info NXi, dans l'éducation nationale, ils passent sur la nouvelle ESR en général à partir de la x.2 ou x.3 donc pas directement.
Mais pour le coup, mon commentaire reste valable ;) :

> Ce serait peut-être pas mal de prévoir un fallback sans JS sur votre navigation, particulièrement le login ...

**Comment by dominiquefournier** [comment]
Et 68 c'est la version stable sur Debian stable...

**Comment by jmuchemb** [comment]
NXi, je vous trop agressifs concernant l'arrêt du support de FF68. Sur smartphone, je n'ai pas envie de jouer les beta-testeurs et il suffit d'aller voir les commentaires sur le playstore pour voir que Mozilla fait encore une fois n'importe quoi et/ou sort un truc pas fini. Bref, j'ai bien l'intention de rester sur Fennec 68.11.0 pendant un moment. Etant abonné depuis plus de 10 ans, ça fait mal.

**Comment by jgachelin** [comment]
Même problème de mon côté, ma boîte n'ayant pas encore poussée la nouvelle version ESR de Firefox, je me retrouve bloqué sur NextInpact (mais pas sur InpactHardware).

**Comment by qwazer14** [comment]
> 
> 
> NXi, je vous trop agressifs concernant l'arrêt du support de FF68. Sur smartphone, je n'ai pas envie de jouer les beta-testeurs et il suffit d'aller voir les commentaires sur le playstore pour voir que Mozilla fait encore une fois n'importe quoi et/ou sort un truc pas fini. Bref, j'ai bien l'intention de rester sur Fennec 68.11.0 pendant un moment.
Parfaitement d'accord, j'utilise la version de Fennec poussée par F-droid, qui n'est pas (encore) mise à jour.
Étant abonné et ne pas avoir accès au site correctement, je trouve ça moyen...

**Comment by pehadavid** [comment]
Un correctif a été appliqué. Cependant, nous vous encourageons fortement à utiliser des versions plus récentes pour des raisons de sécurité. 

De plus, la phase de qualification de Firefox ESR 78 étant passée, il s'agit du dernier correctif que nous pourrons appliquer sur la version 68 ESR.
