### ISSUE TITLE
Lien vers LeBrief sur le fil d'actualité est générique

### ISSUE THREAD

**Issue by DuchkPy** [NextINpact/nextinpactv7#135]
Le lien vers LeBrief du jour sur le fil d'actualité envoie vers https://www.nextinpact.com/lebrief, en cliquant dessus on redirigé vers celui du jour.
De ce fait, demain, le titre dans le fil d'actualité parlera toujours de la même chose, mais le lien renverra vers quelque chose qui n'a rien à voir.

Il faut donc rajouter le numéro du LeBrief dans ce lien.

**Comment by pehadavid** [comment]
Bonjour,

Le titre est  mis à jour à chaque publication. Le lien https://www.nextinpact.com/lebrief renvoie systématiquement vers la dernière édition.
