### ISSUE TITLE
La page du LeBrief ne contient pas la colonne #LeBrief à droite

### ISSUE THREAD

**Issue by DuchkPy** [NextINpact/nextinpactv7#136]
Quand on va sur la page du LeBrief https://www.nextinpact.com/lebrief, dans la colonne de droite, il n'y a que le fil "En continu" de disponible, l'onglet "#LeBrief" a disparu.

**Comment by pehadavid** [comment]
Bonjour,

C'est effectivement le cas (et ce depuis la v6) puisque l'ensemble du Brief est présent sur la page. Cependant, il existe une demande de fonctionnalité pour rajouter le sommaire volant  (voir  #37 )
