### ISSUE TITLE
Retour chariot sur markdown inline code

### ISSUE THREAD

**Issue by Wivik** [NextINpact/nextinpactv7#137]
Hello,

Lorsqu'on veut utiliser l'affichage de code en ligne, des retours chariot sont insérés ce qui détruit le formatage.

Exemple : 

> blablabla \`un truc en format code\` blablabla

Donne : 

> blablabla 
`un truc en format code`
> blablabla

Et non : 

> blablabla `un truc en format code` blablabla

Merci par avance

**Comment by BenjaminINpact** [comment]
c'est réglé ;)
