### ISSUE TITLE
Session déconnectée lors de l'ouverture d'un lien vers un nouvel onglet 

### ISSUE THREAD

**Issue by pitchalov** [NextINpact/nextinpactv7#139]
Sous Firefox ESR 78.x, lors de l'ouverture d'un lien interne Nextimpact dans un nouvel onglet, la session est déconnectée sur le nouvel onglet, et nécessite une reconnexion. Par contre l'ancien onglet avec session en cours reste connecté.

**Comment by pehadavid** [comment]
Duplicate #116
