### ISSUE TITLE
Automatiser l'insertion d'espace insécable dans les articles

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/nextinpactv7#14]
Ceci est un bug que j'avais déjà remplis il y a trèèèès longtemps. 

Actuellement, et depuis longtemps, les espaces insécables ne sont pas utilisées par NXI. Ce qui permet un affichage horrible de ce genre (pris de cet article : beta7.nextinpact.com/article/17173/109184-adevinta-leboncoin-et-ebay-sentremelent)
![image](https://user-images.githubusercontent.com/2286246/88214118-edae4c00-cc59-11ea-9b45-17f0025b586f.png)

Ceci n'est évidemment qu'un exemple parmi des milliers d'autres.

Que ce soit au moment de l'insertion de l'article dans la base, ou au moment de son affichage aux utilisateurs, il faut remplacer tous ces espaces par des espaces fines insécables. 

Règles courtes :  
* avant les signes de ponctuation doubles (:  ;  !  ? % =)
* à l’intérieur des guillemets français («   »)
* entre les prénom et nom d’un auteur
* au sein des nombres (ex : 1 000 000)
* avant les tirets demi cadratin(–)
* entre un nombre et son unité (10 km)
* ...

Pour une version longue de ces règles : https://www.druide.com/fr/enquetes/pour-des-espaces-insecables-impeccables

**Comment by n-e-r-u** [comment]
Très bonne suggestion d'amélioration !

**Comment by papci** [comment]
Nous avons rajouté des outils pour faciliter la gestion des espaces insécables pour les rédacteurs.
