### ISSUE TITLE
Flux RSS avec Brief réduit : #LeBrief des jours passés absents

### ISSUE THREAD

**Issue by Otiel** [NextINpact/nextinpactv7#141]
Voici le contenu du flux RSS récupéré aujourd'hui à 11h30 depuis `https://www.nextinpact.com/rss-complet/241005/[clé-de-sécurité]?reduceBrief=true`

_(dans un paste parce que trop long pour GitHub)_
https://sebsauvage.net/paste/?2a84fb0db694e58f#SC5x9spF6J95GnQ4ZoQZId9QooaOmIKUe3oDMIyZrdM=

Il contient #LeBrief d'ajourd'hui, mais pas ceux des jours précédents.

Alors que le flux RSS avec #LeBrief détaillé contient bien ceux des jours passés (en l'occurence, du 06/10 et du 05/10) :
`https://www.nextinpact.com/rss-complet/241005/[clé-de-sécurité]`

https://sebsauvage.net/paste/?c8781254a3cb3e36#eXJo8s7BpwvnC+QVzuEWW34DFM6qpHYsw64/b4rVWu0=

**Comment by BenjaminINpact** [comment]
C'est fix ! merci du retour btw
