### ISSUE TITLE
Smiley masqué et texte de remplacement affiché

### ISSUE THREAD

**Issue by matthiasbosc** [NextINpact/nextinpactv7#146]
Bonjour, cela fait quelques jours que je remarque que les smileys ne s'affichent plus dans le commentaires, mais à la place leur texte est affiché (par exemple :chinois: ou :craint:)
Si je switch le thème (ex: sombre vers clair), cela fonctionne de nouveau, mais c'est de nouveau cassé après un rafraichissement de la page.
<img width="295" alt="Capture d’écran 2020-10-12 à 15 46 31" src="https://user-images.githubusercontent.com/62800429/95753837-75788500-0ca2-11eb-95d9-c3b590cf5b14.png">

**Comment by ghost** [comment]
Exact, cela me le fait sous Safari et Edge sur le mac (extension désactivée)
Par contre, sur l'iPhone cela s'affiche bien...

**Comment by BenjaminINpact** [comment]
C'est corrigé ! merci à vous pour les retours

**Comment by ghost** [comment]
Cela re-fonctionne bien sur macOS mais pas sur iOS (testé avec Safari et Edge sur iOS14) avec cette page :
https://www.nextinpact.com/article/43761/evolution-exposition-aux-ondes-avec-arrivee-5g-anfr-fait-point

**Comment by ghost** [comment]
C'est bon, cela refonctionne
