### ISSUE TITLE
Ajouter un moyen de "Sauvegarder" / "Marquer" ou "Ajouter aux Favoris" chaque article news etc..

### ISSUE THREAD

**Issue by RamsesDeux** [NextINpact/nextinpactv7#147]
Bonjour a toutes l’équipe de NI.

Je vous lis depuis INpact-Hardware, c'est dire.

Bien souvent il y a un article ou une news que je souhaiterai ajouter dans une liste  ou a mes "favoris".
Mais ajouter la page en tant que favoris dans mon browser c'est pas c'est vite le bordel.

Je me demandais si ajouter une fonctionnalité de favoris de news ou articles serait pertinent pour NI?

L'utilisateur retrouverai sa liste d'articles favoris dans un sous-menu du Hamburger-menu en top gauche.

Un peu comme ci-dessous? (design fait a la va vite en mode dev😅)

Merci de m'avoir lu.
A++

![NI](https://user-images.githubusercontent.com/2408288/95982027-325d1400-0e52-11eb-931f-0a76573b8ede.png)

**Comment by pehadavid** [comment]
Hello,

On a pris la décision de laisser à l'utilisateur de gérer lui même ses favoris il y quelques années maintenant et par conséquent, ça ne reviendra pas ou du moins pas sous cette forme ;)

**Comment by RamsesDeux** [comment]
Merci du retour Pacpi.
