### ISSUE TITLE
Page de commentaires trop large sur smartphone

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#148]
Bonjour,

Cette page est trop large (les autres sont ok) sur mon iPhone (safari ios14)
https://www.nextinpact.com/lebrief/44185/stopcovid-sera-remplace-par-tous-anti-covid-22-octobre#/page/5

Cela doit être dû au lien

**Comment by BenjaminINpact** [comment]
Merci du retour, nous l'avons corrigé.
