### ISSUE TITLE
Le lien vers les commentaires dans le brief ne marche pas

### ISSUE THREAD

**Issue by trou** [NextINpact/nextinpactv7#149]
Firefox 78.3.0esr (64-bit)

Le lien vers les commentaires ne marche pas vraiment, le clic semble ouvrir la news mais ne descends pas au niveau des commentaires.

**Comment by BenjaminINpact** [comment]
Bonjour, 
Cela ne fonctionne qu'en étant connecté et en ayant déjà lu l'article, c'était le cas ?

**Comment by trou** [comment]
j'étais connecté, mais je ne comprends pas le pourquoi du "en ayant déjà lu l'article". J'imaginais que cliquer sur le logo "commentaires" m'ammènerait aux commentaires.

En effet en testant sur un autre brief, cliquer sur "commentaires" dans la page du brief globale amène sur la page de l'article en particulier, et il faut cliquer à nouveau pour atteindre les commentaires. C'est peu intuitif :)

**Comment by BenjaminINpact** [comment]
Une fois que vous avez lu un article, lorsque vous cliquez sur la bulle de commentaire cela vous amène au dernier commentaire lu, le comportement que vous attendez donc. 
C'est un choix de notre part de ne pas orienter directement vers les commentaires quand un utilisateur n'a pas lu l'article. Ce qui nous semble contre intuitif serait de lire des commentaires sur un article non lu même si ça reste faisable en scrollant, on est libre après tout, mais on ne l'encourage pas ;)

**Comment by trou** [comment]
Sauf que dans le cas du brief, j'ai lu l'article dans la page globale :)

**Comment by BenjaminINpact** [comment]
ah oui effectivement dans ce cas là, depuis le brief global, ça parait légitime 🙏

**Comment by BenjaminINpact** [comment]
Merci du retour, du coup c'est bon maintenant :)
