### ISSUE TITLE
Retour arrière qui amène en milieu de page

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#152]
Bonjour,

J'affiche la page avec tous les articles de lebrief, je suis tout en haut sur le premier article. Je clique ensuite sur ce premier pour lire les commentaire et donc je descends dans la page. Puis je clique sur le bouton précédent du navigateur pour retourner sur la liste des articles lebrief du jour. Je me retrouve alors en plein milieu de la page et plus tout en haut...

Testé avec Safari et Edge (macOS et iOS)

**Comment by popileclown** [comment]
J'ai pareil avec Firefox 81.1.4 sous Android 8.0.0

**Comment by BenjaminINpact** [comment]
C'est fixé, merci de vos retours ;)
