### ISSUE TITLE
Page 404 étrange...

### ISSUE THREAD

**Issue by alechapelain** [NextINpact/nextinpactv7#153]
Bonjour,

Pour information, votre page 404 semble avoir un problème sur la version en production:
![image](https://user-images.githubusercontent.com/1588181/97188019-5817e080-17a3-11eb-838e-ad92ba4e3415.png)

![2020-10-26 15_32_41-](https://user-images.githubusercontent.com/1588181/97188242-98775e80-17a3-11eb-9b12-4ed8f70d6343.png)

Vu sur Firefox et Chrome.
Probablement un hack..,?

**Comment by pehadavid** [comment]
Bonjour,

Ce n'est pas un Hack il s'agit d'une référence au célèbre Pulp Fiction de Quentin Tarantino. Cependant, il semble que le climat international actuel soit propice aux mauvaises interprétations. Nous allons donc prochainement retirer ce texte.

**Comment by alechapelain** [comment]
Désolé, j'avais pas la ref ;)

Sinon, vous pouvez laisser et juste indiquer la référence, ca évitera des confusions ! 😄
