### ISSUE TITLE
bug d'identification

### ISSUE THREAD

**Issue by Jaguar-** [NextINpact/nextinpactv7#154]
Bonjour,

sur mon tel android avec webapp firefox, je me suis trouvé identifié en tant que l'utilisateur Eifersucht (je le suis toujours)

j'ai posté et c'est bien le cas ici:

https://www.nextinpact.com/article/44338/itinerance-2g3g-free-et-orange-arguments-bouygues-et-sfr-opposes-a-prolongation

(désolé pour le dérangement)

et sur mon tel j'avais l’impression que votre site s'était fait hacké, il y avait des paroles qui ont défilées quelques secondes

utilisateur NXI: jaguar_fr

**Comment by pehadavid** [comment]
Bonjour,

Est-ce que tu pourrais me contacter par mail ? (pa@nextinpact.com) en me donnant les détails de ton compte (pseudo, c'est noté mais avec ton adresse mail correspondante a ton compte NXi). Je te ferai suivre une procédure en privée afin de voir ce qui cloche.

**Comment by Jaguar-** [comment]
Bonjour Pierre Alain
mon mail NXI est toolinux-pci@yahoo.fr

    Le lundi 26 octobre 2020 à 17:11:58 UTC+1, Pierre-Alain David <notifications@github.com> a écrit :  
 
 


Bonjour,

Est-ce que tu pourrais me contacter par mail ? (pa@nextinpact.com) en me donnant les détails de ton compte (pseudo, c'est noté mais avec ton adresse mail correspondante a ton compte NXi). Je te ferai suivre une procédure en privée afin de voir ce qui cloche.

**Comment by pehadavid** [comment]
Traitement en direct
