### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#156]
Bonsoir,

J'ai souvent l'erreur "502 Bad Gateway" en consultant un profil (mardi 20h40)

<img width="590" alt="Capture d’écran 2020-10-27 à 20 42 15" src="https://user-images.githubusercontent.com/69631254/97353911-ee77ff00-1894-11eb-8579-1e989540c91f.png">

**Comment by BenjaminINpact** [comment]
Hello, 
Ces derniers jours il y a eu beaucoup de 502 car il y a eu pas mal d'attaque sur le serveur comme pour beaucoup de sites en France, ça se calme là, ca devrait rentrer dans l'ordre.
