### ISSUE TITLE
Page de commentaires trop large sur smartphone

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#157]
Bonjour,

Ces page sont trop larges (les autres sont ok) sur mon iPhone (safari ios14)
https://www.nextinpact.com/lebrief/44185/stopcovid-sera-remplace-par-tous-anti-covid-22-octobre#/page/5
https://www.nextinpact.com/lebrief/44393/le-snep-demande-intensification-lutte-contre-streamripping

Cela doit être dû au lien

Déjà signalé dans le https://github.com/NextINpact/nextinpactv7/issues/148 mais ce n'est pas corrigé

**Comment by BenjaminINpact** [comment]
Hello , là c'est corrigé ! merci de ton retour Ecatomb.
