### ISSUE TITLE
les notifications de réponse à un commentaire ne sont pas instananées (loin de là)

### ISSUE THREAD

**Issue by Albirew** [NextINpact/nextinpactv7#158]
Les notifications de réponse à un commentaire arrivent longtemps après les dites réponses.
Pour info, j'ai reçu aujourd'hui 5 notifications de commentaires dont le plus vieux datait du 05/10. Un autre iNpactien parle de 2 semaines.

Voir: https://forum.nextinpact.com/topic/175178-notification-en-r%C3%A9ponse-%C3%A0-un-commentaire-sur-le-site/

**Comment by BenjaminINpact** [comment]
hello,
normalement c'est corrigé.
Merci du retour ;)
