### ISSUE TITLE
[Markdown] conversion des ""

### ISSUE THREAD

**Issue by hwti** [NextINpact/nextinpactv7#16]
Quand je saisis des `"` dans un bloc de code :
\```
"
\```
Le message est :
```
&quot;
```
En éditant le message on peut corriger en remettant un `"`, et ensuite c'est bon.

A l'inverse, des `"` hors bloc de code sont affichés correctement, mais quand on édite le message il affiche `&quot;&quot;`.

**Comment by papci** [comment]
Fixed
