### ISSUE TITLE
Abonnement pas complètement pris en compte sur InpactHardware sur certains appareils

### ISSUE THREAD

**Issue by aurelien-reeves** [NextINpact/nextinpactv7#160]
Je rencontre ce problème sur un PC sous Windows avec Firefox, et sous Android, dans une app épinglée, aussi avec Firefox.

Sous debian, toujours avec Firefox, je n'ai pas le problème.

Sur NextInpact : RAS
Sur InpactHardware, dans certains cas, mon abonnement n'est pas reconnu. Il m'invite à m'abonné. Je crois pourtant avoir accès à l'intégralité des articles, mais j'ai tout de même les encarts qui m'indique "n% de ce contenu reste à découvrir", et quand j'affiche mon profil, sous NI j'ai un lien vers la gestion de mon abonnemenet, sous IH j'ai un bouton "abonnez-vous"

J'ai essayé de rafraichir la web-app sans effet.

**Comment by pehadavid** [comment]
Bonjour, 

Comme indiqué sur la page d'accueil de ce dépot : 

> Si votre problème concerne votre abonnement ou son renouvellement, merci de passer par l'interface de support utilisateur (https://www.nextinpact.com/contact)

**Comment by aurelien-reeves** [comment]
Je n'ai pas de problème avec l'abonnement
Mais avec certaines sessions InpactHardware qui m'affiche certains élément normalement destinés aux utilisateurs non abonnés

Et comme je l'ai précisé, ce n'est pas sur tous mes appareils. J'ai l'impression que ce n'est pas un problème lié à mon abonnement
