### ISSUE TITLE
Bug d'affichage dans les commentaires répondant à une personne

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#161]
J'ai ce problème avec macOS (Safari). Le lien portant le nom de la personne à qui on répond est sur deux lignes alors qu'il n'en prend quasi qu'une seule en réalité...
<img width="399" alt="Capture d’écran 2020-11-05 à 21 52 05" src="https://user-images.githubusercontent.com/69631254/98295194-7787e800-1fb1-11eb-8eab-29350e9f9024.png">

**Comment by ghost** [comment]
Finalement, il n'y a ce problème qu'avec Safari bien qu'il me semblait que Edge faisait pareil... j'ai donc édité mon 1er poste.
Edge à gauche, Safari à droite :
<img width="304" alt="Capture d’écran 2020-11-09 à 20 53 12" src="https://user-images.githubusercontent.com/69631254/98589532-ba0d3580-22cd-11eb-91d1-8e0d8bd28d40.png">

**Comment by BenjaminINpact** [comment]
C'est corrigé 👍

**Comment by ghost** [comment]
Toujours le problème avec Safari ou Edge sur macOS... J'ai supprimé les caches pour ce test

<img width="264" alt="Capture d’écran 2020-11-19 à 21 38 25" src="https://user-images.githubusercontent.com/69631254/99721467-92795280-2aaf-11eb-8856-046e6cb76f34.png">

**Comment by ghost** [comment]
Aujourd'hui c'est bon 😊
