### ISSUE TITLE
Impossible de commenter un article

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#162]
J'ai l'erreur suivante si j'essaye de poster un commentaire. C'était sur une news du lebrief d'aujourd'hui
<img width="846" alt="Capture d’écran 2020-11-06 à 21 54 35" src="https://user-images.githubusercontent.com/69631254/98413914-c5b4ee00-207a-11eb-827b-d92320e871af.png">

D'autres personnes ont le même soucis. Ils sont venus sur le forum en parler.

**Comment by pehadavid** [comment]
C'est corrigé ;)
