### ISSUE TITLE
Le retour en arrière depuis un article du brief ne revient pas au fil « en continu »

### ISSUE THREAD

**Issue by Borgnasse** [NextINpact/nextinpactv7#164]
Sur mobile, iOS 14.1

Depuis la page principale, onglet « en continu ». 
On clique sur un brief d’un jour quelconque. 
Si on revient en arrière on revient bien sur la page principale nextinpact dans l’onglet « en continu »

Depuis la page principale, onglet « en continu ». 
On clique sur un brief d’un jour quelconque.
On clique ensuite sur un item quelconque du brief. 
Si on revient une fois en arrière on retombe bien sur la page du brief complet. 
Mais si cette fois on revient une deuxième fois en arrière, au lieu de tomber sur la page principale nextinpact sur l’onglet « en continu », on tombe sur la page principale sur l’onglet « le brief ». 

A priori ça n’est pas spécialement cohérent.

**Comment by BenjaminINpact** [comment]
C'est corrigé, merci du retour.
