### ISSUE TITLE
Affichage de la page trop large à cause du texte d'un article

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#166]
Bonjour,

Avec Safari sur iOS14, l'affichage de page suivante a un léger bug : le nom à rallonge de la variable est trop long et n'a pas de retour à la ligne. Cela déforme l'affichage
https://www.nextinpact.com/lebrief/44573/visual-studio-code-1-51-est-la-avece-echo-local-pour-terminal

![IMG_4025](https://user-images.githubusercontent.com/69631254/98815839-09677900-2428-11eb-91a8-fedd4b417747.jpeg)

**Comment by BenjaminINpact** [comment]
C'est corrigé ;)
