### ISSUE TITLE
Commentaires impossible

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#168]
Bonjour,

Pas de chance ce vendredi 13, impossible de mettre un commentaire dans un article du brief...

J’ai l’erreur suivante lors de l’envoi:
« Une erreur est survenue lors de l'envoi de votre commentaire. Veuillez réessayer ultérieurement. »

**Comment by ghost** [comment]
Cela refonctionne pour le moment en tout cas.

**Comment by BenjaminINpact** [comment]
Hello, 
Cela vient de personnes sournoises qui tentent de surcharger le serveur. On a fait un hot patch pour soulager et on monitore... 
Merci de tes retours ;)
