### ISSUE TITLE
Sous-titre en gras ?

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#169]
Bonjour,

Dans cet article :
https://www.nextinpact.com/article/44560/reseaux-sociaux-senat-etend-bigbrotherbercy-a-lutte-contre-fraude-sociale

J'ai l'impression que ce sous-titre n'est pas en gras pour la partie en italique...

![IMG_4068](https://user-images.githubusercontent.com/69631254/99083335-b297a600-25c5-11eb-9128-7d7eb4bee880.jpeg)

**Comment by pehadavid** [comment]
Hello merci pour la remontée, on va voir ce qu'on peut faire de notre coté, mais il s'agit d'un problème avec notre typo qui ne supporte la combinaison italique + gras. Pas sur qu'on puisse corriger, mais théoriquement il ne devrait pas y avoir ce genre de de chose dans les intertitres ;)
