### ISSUE TITLE
Notification de réponse qui revient régulièrement

### ISSUE THREAD

**Issue by OliverFrWTFalreadyTakenComeOnNow** [NextINpact/nextinpactv7#170]
Bonjour. Pas habitué des trackers, github & tout, désolé si je manque à certains usages !

Sur NxI, chaque fois que je reviens sur le site, j'ai en haut à droite un gros (1) en rouge, et quand je clique dessus, à l'emplacement de mon avatar, ça me dit qu'il y a eu une réponse/quote à un commentaire que j'ai écrit sous une news.

Cliquer sur la notification de réponse supprime le (1) rouge de notification. Mais : si je ferme NxI, la fois suivante où je suis de retour sur le site, il y a de nouveau la notification.

Plus d'informations :

- Firefox dernière version stable actuelle, Windows 10 home, extension UblockOrigin avec options de base
- Reproduction ? Oui : ça arrive systématiquement. Mais non : dur à reproduire: il semble qu'il faille ne pas revenir sur NxI pendant un certain temps pour que la notification soit de retour, si je ferme l'onglet, puis rouvre le site une minute plus tard, la notif n'est pas encore revenue.
- Depuis quand : depuis qu'a été réglé le problème de l'absence de visibilité des notifications de réponse sur NxI dans Firefox. Précision : avant ça, quand on cliquait sur son avatar, ça nous disait déjà bel et bien qu'on avait reçu une réponse. Mais : il n'y avait pas de (1) rouge visible sans avoir à ouvrir la liste des notifications.
- Nom d'utilisateur NxI : sabinoo
- La réponse qui génère à chaque fois une notification : https://www.nextinpact.com/article/44650/le-recap-bons-plans-moment-semaine-47#comment/1837536

- EDIT ultérieur : au cas où l'info est pertinente, pile après avoir enfin pris les dix minutes pour poster le machin sur Github, paf, ça ne se produit plus désormais ¯\_(ツ)_/¯

Voilà voilà, bon courage, et bonne journée à qui me lira :)

**Comment by BenjaminINpact** [comment]
Ok, peut être un problème de cache. Si ca se reproduis ,n'hésitez pas à nous recontacter :)

**Comment by jotak** [comment]
Perso je vois ça régulièrement aussi. Mes notifs restent souvent visibles après consultation du lien. Et puis, au bout d'un moment (parfois plusieurs jours), ça fonctionne elles disparaissent, sans que je comprenne trop pourquoi. Ça me semble assez aléatoire.
