### ISSUE TITLE
Numéro de page des commentaires

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#172]
Bonjour,

Le champ pour sélectionner la page de commentaire de son choix bug avec une certaine taille de la page.
Si c'est plus grand, la partie inclinée est bien accolée au reste. Si c'est plus petit, elle est cachée.

<img width="180" alt="Capture d’écran 2020-11-22 à 14 55 21" src="https://user-images.githubusercontent.com/69631254/99905797-60483a80-2cd3-11eb-8b26-d7fb667d6fb3.png">

**Comment by BenjaminINpact** [comment]
hello ;) C'est fix !
