### ISSUE TITLE
Sommaire immobile pour les bons plans

### ISSUE THREAD

**Issue by bansan85** [NextINpact/nextinpactv7#174]
URL: https://www.nextinpact.com/article/44771/le-recap-bons-plans-moment-semaine-48

Testé sur Windows, Firefox 83.0

On a bien le sommaire avec la liste des paragraphes. Quand on clique dessus, on est bien renvoyé vers le bon paragraphe.

Par contre, quand on défile avec la molette de la souris, l'indicateur orange reste figé au premier paragraphe.

![image](https://user-images.githubusercontent.com/9248729/101236200-7a204f00-36cf-11eb-8003-8d730eb319b0.png)

**Comment by bastien-c** [comment]
Bonjour, merci pour votre retour c'est corrigé.
