### ISSUE TITLE
Style manquant pour le titre d'un article "Brief"

### ISSUE THREAD

**Issue by PerfectSlayer** [NextINpact/nextinpactv7#176]
Bonjour,

Je constate que quelque soit le navigateur que j'utilise (le dernier Firefox ou Chrome), il manque le style du titre des articles de "LeBrief" lors que celui-ci est lu indépendamment. Cela ne se produit que lorsque je suis connecté et que mon thème (yingyang sombre) est utilisé.

Capture : 
![image](https://user-images.githubusercontent.com/1766222/101908423-5c198980-3bbc-11eb-9142-d5f9e0db61ed.png)
Source : https://www.nextinpact.com/lebrief/45010/la-ftc-accuse-facebook-maintenir-illegalement-son-monopole-qui-lui-repond-quelle-est-revisionniste (mais c'est valable quelque soit l'article de "LeBrief")

Alors que ça s'affiche bien quand j'affiche "LeBrief" de la journée :
![image](https://user-images.githubusercontent.com/1766222/101908606-9be07100-3bbc-11eb-9f17-b28218db7e17.png)
Source : https://www.nextinpact.com/lebrief/688

Merci à vous et bonne continuation 😉

**Comment by bastien-c** [comment]
Bonjour, merci pour votre retour c'est corrigé.
