### ISSUE TITLE
Date des commentaires dans les articles archivés fausse

### ISSUE THREAD

**Issue by bansan85** [NextINpact/nextinpactv7#178]
Bonjour,

En allant sur de vielles archives (https://www.nextinpact.com/archive/Homosexualite_cachee_Attention_aux_ordinateurs_.htm) du 22 août 2004 à 13:33, le premier commentaire a la date "14/10/14 à 14:37:04"

Idem pour un autre exemple (https://www.nextinpact.com/archive/Du_nouveau_sur_la_PSP_de_Sony_une_date_de_sortie_.htm) du 14 janvier 2005 à 13:20, le premier commentaire a la date "07/05/15 à 11:09:19"

Ni le jour, le mois ou l'année ne sont bon. Pour le second exemple, l'heure n'a pas l'air d'être bonne non plus. Au vu de la vitesse des commentaires, ça m'étonnerait que le premier ait mis 20h et les suivants 10 minutes entre chaque.

**Comment by pehadavid** [comment]
C'est corrigé (les archives n'ont pas de commentaires)
