### ISSUE TITLE
Fonctions répondre/citer en mode de prévisualisation

### ISSUE THREAD

**Issue by hwti** [NextINpact/nextinpactv7#18]
Si pendant la prévisualisation d'un message, on fait un clic sur un bouton répondre ou citer, il y a une erreur JS : `ERROR TypeError: can't access property "selectionEnd", e is null`.
Ensuite, même après avoir quitté la prévisualisation, la fonction utilisée est inopérante (sans trace d'erreur) tant qu'on n'a pas rechargé la page.

**Comment by papci** [comment]
Fixed
