### ISSUE TITLE
#LeBref: accès via le calendrier impossible avant le 02/Nov/2020

### ISSUE THREAD

**Issue by bansan85** [NextINpact/nextinpactv7#183]
Bonjour,

Depuis la correction de #36 le calendrier ne fonctionne plus avant novembre 2020. Les dates sont toutes grisées.

Testé sur Android et PC, Chrome et Firefox.

**Comment by pehadavid** [comment]
Bonjour, ce n'est pas un bug, la possibilité de remonter aux briefs antérieurs est limité  pour des raisons techniques.

**Comment by bansan85** [comment]
C'est dommage et ça fait bizarre sur le site mais OK je comprends.
