### ISSUE TITLE
Formulaire de contact HS

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#184]
Bonjour,

Le formulaire de contact sur le site ne fonctionne plus 
https://www.nextinpact.com/contact

J'ai testé avec 2 types de demandes et rien ne se passe lorsque je clique sur "envoyer" (bien que le captcha soit validé). J'ai testé avec Safari et Edge sur macOS

Merci

**Comment by pehadavid** [comment]
c'est corrigé ;)
