### ISSUE TITLE
INpact Hardware en partie disparu sur le site Next INpact

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#185]
Bonjour,

Il n'y a aucun article INpact Hardware entre le 27/01 et le 29/01 dans les actualités de Next INpact.
J'ai testé pas acquis de conscience de cocher toutes les cases d'affichages (y compris pub), mais cela ne les a pas fait apparaitre par magie. Donc cela va être un peu plus complexe à résoudre 😉

Les article sont pourtant bien visibles sur IH

Bonne journée

ps: merci à SebDel71 pour en avoir parlé sur le forum

<img width="693" alt="Capture d’écran 2021-02-01 à 19 35 47" src="https://user-images.githubusercontent.com/69631254/106503263-b4d31780-64c5-11eb-8679-765d41760ed9.png">
<img width="781" alt="Capture d’écran 2021-02-01 à 19 40 32" src="https://user-images.githubusercontent.com/69631254/106503271-b7357180-64c5-11eb-9c79-d6ee9f59455f.png">

**Comment by pehadavid** [comment]
Hello, 

Ce n'est pas un bug. L'équipe rédactionnelle a simplement choisi de ne pas faire apparaitre certains articles IH sur NXi. 

Bonne soirée.
