### ISSUE TITLE
Bouton de connexion désactivé

### ISSUE THREAD

**Issue by ColinMaudry** [NextINpact/nextinpactv7#186]
Le bouton de connexion est désactivé, impossible de se connecter.

L'onglet des devtools indique des erreurs CORS avec l'API NextINpact.

Je suis sous Firefox.

**Comment by pehadavid** [comment]
Bonjour,

Je ne reproduis pas, des extensions en particulier qui pourraient bloquer ?

**Comment by ColinMaudry** [comment]
Hello !

Bon je viens de rafraichir, et le problème est parti.

uBLock origin était désactivé.

Merci pour la réactivité !
