### ISSUE TITLE
[2FA] Ajouter Webauthn aux comptes Nextinpact

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#187]
Coucou,
Je demande simplement l'implémentation de la validation en deux étape Webauthn (Ubikey).

infomation supplémentaire : 
Dans le cas de webauthn ne pas oublier (si implémenté) de permettre d'ajouté plusieurs clef car beaucoup (comme moi) ajoute celle de l'os (windows hello) ainsi qu'une ubikey de "secours" afin de récupéré le compte en cas de perte de l'os.

But final : 
L'implémentation de webauthn en tant que validation en deux étape serait le premier pas vers le passwordless, vers le quel internet commence a se diriger (microsoft, google, etc).

Merci 👍

**Comment by pehadavid** [comment]
Bonjour,

C'est un sujet auquel nous pensons régulièrement, ça arrivera mais pas tout de suite ;)

**Comment by ghost** [comment]
> Bonjour,
> 
> C'est un sujet auquel nous pensons régulièrement, ça arrivera mais pas tout de suite ;)

Avancée sur le sujet ?

**Comment by pehadavid** [comment]
Hello,

C'est toujours prévu mais le développement n'est pas encore planifié.
