### ISSUE TITLE
[Fonction] Filtrage des non abonnés

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#188]
## Problème
Depuis quelques mois, l'apparition de troll et activiste extrémiste dans les commentaires se fait de plus en plus fréquents et cela commence a agassé plusieurs utilisateurs abonnés (de ce que j'ai vu en commentaires, cela n'est peut être pas généralisé).

J'aimerais une nouvelle fonction basée sur celle de Ghack ou la totalité des commentaires sont vérifier avant publication mais dans une forme plus "adaptée" a next inpact.
Les dit commentaire viennent très règulièrement de nouveau compte créer spécialement pour l'occasion.

## Fonction souhaitée
Imposé une limite de temps avant de pouvoir commenter sur les nouveau compte et imposé un vérification des commentaires (ou  n'importe quel filtre que l'équipe nextinpact trouvera plus adapté) au utilisateur non abonné (car les utilisateurs abonné sont plus mesuré car un ban leur fait perdre leur abonnements).

## Alternative possible
Obliger aux utilisateurs non abonné de lier un numéro de téléphone a leur compte s'il souhaite pouvoir commenté, ainsi, en cas de banissement pour un des motif mentionné plus tot (troll, extrémisme ou tout motif de banissement selon les CGU) leurs numéro de GSM sera banni en même temps, ils leurs sera donc plus difficile a ces personne de recréer un compte pour venir "pourrir" les commentaires.

## Explication
Je sais pertinement que de demandé au non abonnés de lié leur numéro pour commenter pourrais sonné comme étant poussé l'utilisateur a fournir une donnée personnelle.
Cependant cela fait maintenant plusieurs années que je suis abooné a nextinpact, et je commence a en avoir assez de me faire insulté/rabaissé par des "troll" en commentaire tout fraichement sorti de voici ou numérama venant faire leur SJW en commentaire.

Merci de m'avoir lu.

**Comment by pehadavid** [comment]
Merci pour la suggestion, mais cela ne rentre pas du tout dans notre politique de modération et de liberté d'expression.
