### ISSUE TITLE
erreur contextuelle

### ISSUE THREAD

**Issue by fretere** [NextINpact/nextinpactv7#189]
Bien que l'option soit cochée dans les paramètres (Signalement d'erreur contextuel), ça ne marche pas.
Il faut décocher/recocher pour que le menu "Signalement d'erreur contextuel" apparaisse.

**Comment by BenjaminINpact** [comment]
Hello,
On a corrigé ce comportement, merci pour ton retour.

**Comment by fretere** [comment]
Bonjour,
Ce n'est pas réglé pour moi même après déconnexion/reconnexion...

Le lun. 22 mars 2021 à 10:10, BenjaminINpact ***@***.***> a
écrit :

**Comment by BenjaminINpact** [comment]
Effectivement, mon test n'était pas complet ... mais c'est solutionné de notre coté maintenant. Cela passera à la prochaine mise à jour.
