### ISSUE TITLE
Boutons sociaux désactivés mais plugin twitter chargé

### ISSUE THREAD

**Issue by srbetasign** [NextINpact/nextinpactv7#19]
Bonjour,

ayant décoché les "boutons sociaux" dans les paramètres, je constate depuis Privacy Badger sous Firefox que le plugin "platform.twitter.com" de Twitter est toujours chargé.

Bonne journée

**Comment by papci** [comment]
Bonjour,

Le script twitter ne se charge pas à partir des boutons sociaux (qui sont des boutons natifs et non des ressources tierces) mais a partir des tweets intégrés dans les actus.
