### ISSUE TITLE
"Si vous voulez témoigner" en fin d'article : apparaît barré en responsive

### ISSUE THREAD

**Issue by kao98** [NextINpact/nextinpactv7#193]
![image](https://user-images.githubusercontent.com/2054625/111295983-43ea5800-864c-11eb-8f1c-54544b47784c.png)

(Firefox)

Il y a deux `<div id="disc-container"` inbriqués, ce qui n'aide pas le navigateur à appliquer les styles correctement.

En changeant un des deux ids, la mise en page est réparée

**Comment by BenjaminINpact** [comment]
merci du retour kao98, c'est corrigé.
