### ISSUE TITLE
Mode de lecture immersive avec NextINpact (et INpact-Hardware) non disponible avec MS Edge

### ISSUE THREAD

**Issue by MilesTEG1** [NextINpact/nextinpactv7#194]
Bonjour,
Je souhaiterais utiliser le mode de lecture immersif de MS Edge (j'ai la dernière version disponible à ce jour), mais ce n'est pas possible car le bouton n'est pas présent.
![image](https://user-images.githubusercontent.com/29298312/111620050-88a9f680-87e6-11eb-861d-c85bd6b385ae.png)
![image](https://user-images.githubusercontent.com/29298312/111620192-ad05d300-87e6-11eb-92fd-fd8a9f6eedb3.png)

Sur d'autres sites, ce mode immersif est disponible : 
![2021-03-18 12_37_54](https://user-images.githubusercontent.com/29298312/111620440-02da7b00-87e7-11eb-813e-cee013ffcef9.png)

Serait-il possible de faire en sorte que ce mode soit disponible ?

PS : je suis sous windows 10 20H2, dernière version stable.

**Comment by pehadavid** [comment]
Le probleme semble plutot être coté Edge qui ne détecte pas le contenu : peut-être un manque de support  des Progressive Web App pour ce mode.

**Comment by MilesTEG1** [comment]
Bonjour,
Je veux bien que le soucis vienne de Edge, mais du coup, si le mode immersif fonctionne avec d'autres sites, pourquoi ne fonctionne-t-il pas avec NextINpact/Hardware-INpact ?
