### ISSUE TITLE
Le flux RSS envoie vers une erreur 404

### ISSUE THREAD

**Issue by 16mhz** [NextINpact/nextinpactv7#195]
Bonjour,

Comme en Septembre dernier (cf [#105](https://github.com/NextINpact/nextinpactv7/issues/105)), les flux RSS ne semblent plus fonctionner alors que je suis bien abonné jusqu'en 2023.
Je tombe sur la [page 404](https://www.nextinpact.com/404). J'ai essayé de réinitialiser la clé de sécurité mais sans succès.

Je ne sais pas si je suis le seul concerné par le souci.

Merci d'avance.

**Comment by pehadavid** [comment]
Bonjour,

Merci pour la remontée. Les flux doivent fonctionner correctement. Est-ce que le problème est présent avec un agrégateur de RSS ? Si oui il vaut mieux contacter le support afin de voir s'il n'y a pas un problème spécifique au compte.
