### ISSUE TITLE
[Commentaires] Améliorer le fil des commentaires

### ISSUE THREAD

**Issue by HenriTEL** [NextINpact/nextinpactv7#196]
* Les commentaires sont fermés sous la plupart des articles
* Il manque la possibilité d'upvote/downvote pour faire ressortir les commentaires les plus pertinents
* La hiérarchie n'est pas claire entre les nouveaux commentaires, les réponses à des commentaires et les mentions de membres.

**Comment by pehadavid** [comment]
Bonjour,

> Les commentaires sont fermés sous la plupart des articles

Les commentaires sont ouvert pendant les 7 premiers jours suivant la diffusion d'un article et réservés aux abonnés lorsque l'article est également réservé aux abonnés.

> Il manque la possibilité d'upvote/downvote pour faire ressortir les commentaires les plus pertinents

Nous avons déjà expérimenté un tel système mais rien de positif n'en est sorti (bashing par downvote,  appel à la popularité etc.). Il n'est donc pas à l'ordre du jour de le réintroduire. 

> La hiérarchie n'est pas claire entre les nouveaux commentaires, les réponses à des commentaires et les mentions de membres.

Les commentaires sont triés par date d'ajout. Un système de "thread" était présent mais nous avons décider de ne pas le reconduire en v7 car extrêmement peu utilisé.
