### ISSUE TITLE
demande de m'abonner alors que je viens de me réabonné

### ISSUE THREAD

**Issue by Grummfy** [NextINpact/nextinpactv7#199]
Bonjour,
alors que je viens de me réhabonné, j'ai le bloc abonnez-vous en haut a droite.
J'ai le bloc voir plus de contenu (alors que le contenu est là)
![Screenshot_2021-04-20 GandiCloud VPS (OpenStack) une offre repensée, que faut-il en retenir ](https://user-images.githubusercontent.com/668804/115391920-4c502880-a1e0-11eb-96a2-fd00f6b09b4c.png)

je suis sous firefox (au cas où)
un ctrl+f5 n'a rien changé

me déconencté et reconnecté a résolu le soucis

**Comment by BenjaminINpact** [comment]
Hello, surement un problème transitoire, le réabonnement est bien pris en compte normalement.
