### ISSUE TITLE
Corps de page non-centré sur la page d'accueil lors du passage à plusieurs fenêtre sur windows

### ISSUE THREAD

**Issue by DuchkPy** [NextINpact/nextinpactv7#20]
Lors du déplacement de la fenêtre firefox 78.0.2 d'un côté ou de l'autre de l'écran sur Windows, l'affichage n'est pas centré ni ne rempli tous l'écran.
Ce soucis ne se produit pas quand on réduit/augmente la fenêtre jusqu'à la même taille. Aussi, je n'ai vu ce soucis que sur la page d'accueil.
Je suis sur un écran 27", 2560 x 1440

![capture1](https://user-images.githubusercontent.com/36851093/88271491-7ddea680-ccd7-11ea-98ce-8900c404c0e7.PNG)

**Comment by papci** [comment]
Fixed
