### ISSUE TITLE
Lien discord hs

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#200]
Bonjour,

Ce lien Discord semble HS :
<img width="204" alt="Capture d’écran 2021-04-22 à 19 45 28" src="https://user-images.githubusercontent.com/69631254/115762036-4f474680-a3a3-11eb-8bea-2dd9ba1d6bf3.png">

Merci de le corriger

**Comment by BenjaminINpact** [comment]
Hello, 
Merci du retour, il sera corrigé à la prochaine mise à jour.
