### ISSUE TITLE
Manque d'autofocus sur le champ de recherche

### ISSUE THREAD

**Issue by Nozalys** [NextINpact/nextinpactv7#202]
## Description du problème :
Bonjour,

Il manque un autofocus sur le champ de recherche. Que ça soit sur Edge ou Firefox, il faut cliquer une première fois sur l'icône de la loupe pour rendre visible le champ de texte, puis à nouveau cliquer dans le champ de texte pour pouvoir commencer à écrire dedans.

## Proposition de solution :
Donner le focus automatiquement au champ de recherche lors du clic sur l'icône de la loupe.

## Environnement :
```
Firefox : Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
Edge : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134
Javascript activé
Cookies activés
```

**Comment by BenjaminINpact** [comment]
Hello, 
Merci du retour Nozalys, effectivement, on va améliorer ce comportement.
