### ISSUE TITLE
Exploration des contenus en accès libre : feature "un jour sans fin"

### ISSUE THREAD

**Issue by DanLo-peratingSystem** [NextINpact/nextinpactv7#203]
Hello,

### Description
Comme mentionné sur le discord [ici](https://discord.com/channels/88569538362249216/88569538362249216/843156348484845578), je viens de constater un bug (visible uniquement pour les non-abonnés je crois) sur la page récapitulative des articles en accès libres [ici](https://www.nextinpact.com/acces-libre) : 
![image](https://user-images.githubusercontent.com/11614445/118372492-2edd6700-b5b2-11eb-9836-989dfcaca3b3.png)

### Comment reproduire le problème
En naviguant avec les flèches de l'interface, je constate qu'arrivé à la page 2, il est impossible d'accéder aux pages suivantes, un clic montre bien l'url de la page 3 (_[...]/acces-libre/page/3_) mais le contenu reste exactement celui de la page 2.
La navigation avec les boutons devient complètement cassées suite à cela (c.f. gif ci-dessous).
En forçant l'url (taper directement celui de la page 3 et appuyer sur `Enter` dans la barre d'adresse) permet d'afficher effectivement la bonne page.
![](http://g.recordit.co/1xrjYMME93.gif)

### Informations techniques :
**Navigateur** : Firefox 
**OS** : Windows 10
sans extensions notables d'activées quand je suis sur le site.

**Comment by BenjaminINpact** [comment]
Hello, merci du retour, c'est en cours de résolution (à la prochaine maj ;) )
