### ISSUE TITLE
Options de filtrage sur forum en doublon, ou mal nommées

### ISSUE THREAD

**Issue by OliverFrWTFalreadyTakenComeOnNow** [NextINpact/nextinpactv7#205]
Un bug report express car dodo time, cf. la capture d'écran jointe

URL : https://forum.nextinpact.com/
Cliquer "rechercher" en haut à droite, observer le menu qui s'affiche
Browser: Firefox 89
Windows 10

Bonne journée !
![nextinpact forum](https://user-images.githubusercontent.com/29028445/121095236-3d552200-c7f0-11eb-9aef-d760da35e3e7.jpg)

**Comment by pehadavid** [comment]
Hello,

Le forum est géré par la communauté, il faut mieux leur adresser le bug directement ;)
