### ISSUE TITLE
Page 404 -- Mentions légales et contact

### ISSUE THREAD

**Issue by jonezime** [NextINpact/nextinpactv7#206]
Le lien "Mentions légales et contact" accessible depuis le footer de la page "Bons plans" retourne une 404

`<a _ngcontent-bptech-c33="" href="https://www.nextinpact.com/a-propos.htm#nouscontacter_section" target="_blank" rel="noopener">Mentions légales et contact</a>`

**Comment by BenjaminINpact** [comment]
Hello, 
Merci de ton retour, nous allons corriger cela.

**Comment by BenjaminINpact** [comment]
Le correctif est passé ;)
