### ISSUE TITLE
Bug du menu de droite (liste article et lebrief)

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#207]
Bonjour,

Le menu à droite listant les articles et les mini articles de lebrief fonctionne plutôt bien.
Mais s'il y a deux choix "en continue" et "#lebrief" (donc qu'on est en train de lire un article), l'affichage des mini-articles de lebrief est coupé à un moment. Comme sur cette capture, il manque la partie concernant les commentaires.

Problème avec Safari ou Edge sous macOS

<img width="680" alt="Capture d’écran 2021-06-17 à 19 06 37" src="https://user-images.githubusercontent.com/69631254/122443142-91ee5f00-cf9f-11eb-860e-efeb2bc007d9.png">

**Comment by BenjaminINpact** [comment]
Hello Ecatomb, 
Merci de ton retour, effectivement la bulle du nombre de commentaire n'est pas visible, on va corriger cela.

**Comment by BenjaminINpact** [comment]
C'est corrigé également ;)
