### ISSUE TITLE
Vidéo trop large sur iOS

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#208]
Bonjour,

Dans cet article, la vidéo dépasse la largeur de l'article
https://www.nextinpact.com/article/46246/les-controleurs-europeens-veulent-interdire-surveillance-algorithmique-masse

Résultat :
![IMG_4854](https://user-images.githubusercontent.com/69631254/123519285-817a6a80-d6aa-11eb-86a2-1af398ab4268.jpeg)

**Comment by BenjaminINpact** [comment]
Hello Ecatomb,
Merci de ton retour, c'est corrigé, ce n'était pas exclusif à iOS en plus.
