### ISSUE TITLE
Two step validation

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#209]
Etant donné qu'il est devenu fortement recommandé par les autorité "traditionnel" (entendre par la largement incompétente en tech) d'activer la validation en deux étape partout ou elle est disponible, je trouve extrêmement étrange de voir un journal orienté tech ... ne pas la proposé pour ses comptes.

Je sais que vous ne stocké pas des données digne de fort Knox mais bon montré l'exemple toussa toussa.

**Comment by pehadavid** [comment]
Comme dit dans #210, nous prévoyons de mettre en place Webauthn a moyen terme.
