### ISSUE TITLE
Connexion automatique nouvel onglet lente

### ISSUE THREAD

**Issue by darkweizer** [NextINpact/nextinpactv7#21]
Depuis toujours sur HI mais également présent sur la v7 (logique vu que c'est la même base...), quand j'ouvre un nouvel onglet du site, je ne suis pas tout de suite connecté. J'ai donc la page blanche sans thème (qui me tue les yeux au passage ^^) puis connexion et passage au thème sombre.
Et comme je ne navigue pratiquement que comme ça, en ouvrant dans de nouveaux onglets de ce que je veux voir, c'est très très gênant (pour resté poli 😅. Mais c'est une des raisons pour lesquels je ne vais jamais sur HI d'ailleurs).

[Un petit gif montrant le soucil](https://ibb.co/TbTn91q). Avec Firefox, mais depuis de nombreuses versions ^^.
[http://supportdetails.net/E73UM41B](http://supportdetails.net/E73UM41B) j'ai le même souci avec 2 autres ordi mais toujours sur Firefox.
P.S.: Je viens de tester avec Edgium (et uBlock comme sur mon Firefox) et aucun souci, je suis directement connecté sur les nouveaux onglets.

**Comment by papci** [comment]
Hello,

As-tu des extensions particulières ? Dans la console du navigateur as-tu des erreurs ?

**Comment by darkweizer** [comment]
[Voici ce que je vois dans la console](https://ibb.co/K9btYWJ).
On voit bien qu'il y a déconnexion. 
Ça le fait même pendant la navigation sur le même onglet en fait.
Alors oui j'en ai tout un tas [https://ibb.co/txh6vVM](https://ibb.co/txh6vVM) ! Mais je les ai tous désactivés pour tester, reboot de Firefox et pareil.
J'ai également repassé le paramètre **Protection renforcée contre le pistage** de Personnalisée (avec tout de coché) à Standard mais rebelote, ce souci de reconnexion systématique.
J'ai désactivé mon anti-virus (Kaspersky Anti-Virus 2020), pas de changement.

**Comment by papci** [comment]
Des améliorations ont été portées. Si vous ne constatez, pensez a fermer votre navigateur et a le réouvrir (voire a patienter un peu) car cela dépends des DNS ;)

**Comment by darkweizer** [comment]
Effectivement, ça à l'air de beaucoup mieux fonctionner maintenant 😊.
Je n'ai qu'un de mes ordis pour tester actuellement (et pas le moins rapide) mais il n'y a pas de raison !
Nickel, merci 🙂👍🏻👌🏻

**Comment by Sheepux** [comment]
Je confirme que c'est plus mieux !
