### ISSUE TITLE
Login with apple

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#210]
Dans la même trempe que la demande précédente voir le retours des connexion tiers serait grandement appréciée.
Surtout (comme indiqué dans le titre) login with apple, qui permet un login sécurisé (forçant la validation en deux étape apple), et créant un email anonyme rediriger vers notre boite (pour les utilisateurs apple).

Enfin je milite également pour le retours des connexion via Google et Facebook (meme si je ne suis pas client de ces dernier) pour les même raison que celle d'apple (être protéger par le niveau de sécurité du compte Apple / Google / Facebook.

Surtout que comme dit dans l'issue : https://github.com/NextINpact/nextinpactv7/issues/209 vous ne proposez pas vous même de validation en deux étape, cela serait la méthode la plus simple de la proposé.

Evidement n'oublier pas la conversion des compte existant (supprimé l'accès via mots de passe (sinon l'intérêt deviens nulle étant donné que la sécurité peut peut être contourné via un simple password)).

Merci d'avance.

**Comment by pehadavid** [comment]
Hello,

Nous avons fait les choix de retirer progressivement les  fonctionnalités de connexion via des tiers pour poursuivre notre  réduction des dépendances aux GAFAM. Leur retour n'est donc pas envisageable. En revanche, nous prévoyons d’implémenter Webauthn pour renforcer la sécurité des comptes.

**Comment by ghost** [comment]
@papci Anti gafam primaire ... au lieu de protéger la sécurité/vie privée peut importe quel technique est utilisée.

Enfin je vous rappel qu'un bouton login with apple, ne vous rend pas Dependant d'eu ca laisse juste le choix (chose qui vous parait inconnu) a vos "clients" ... bref, sachez que je ne suis pas en adéquation avec ces choix politique anti gafam de votre part.

Sans oublier qu'en implémentant que webauth et non OTP et autre technique en deux étape, vous aller juste (encore une fois) jeter sur le bord de la route tous ceux ne disposant pas de windows 10 ou une clef d'authentification physique bravo vous qui vous présentez pro sécurité, vie privée, etc. ca fait tache sur votre tableau vous ne trouvez pas ?

Mais c'est bien connus les linuxiens et utilisateur a la pomme n'existe pas.

Je n'attend pas de réponse, mais sachez que vous venez de perdre un abonné (je ne renouvellerais plus, j'hésitais depuis la V7 (horrible a tous les niveau) mais maintenant mon chois est fait)
