### ISSUE TITLE
Une erreur est survenue lors de l'envoi de votre commentaire

### ISSUE THREAD

**Issue by sedirae** [NextINpact/nextinpactv7#216]
Bonjour,

Quand je souhaite poster un commentaire, je rencontre le message suivant : 

"Une erreur est survenue lors de l'envoi de votre commentaire. Veuillez réessayer ultérieurement."

Mon abonnement est valide, j'ai essayé sur différents navigateurs, déco/reco, vidé le cache (+dns) et j'ai retenté à plusieurs semaines d'intervalles mais rien n'y fait.

J'ai cherché sur github mais rien trouvé de très probant, j'ai loupé un truc ou il y a vraiment un couac avec mon compte?
En vous remerciant pour vos réponses/actions.

**Comment by pehadavid** [comment]
Bonjour,

ça semble être spécifique avec ton compte, le mieux serait de contacter sur le support (https://www.nextinpact.com/contact)
