### ISSUE TITLE
Aucune image affichée sur iPad Pro

### ISSUE THREAD

**Issue by stephenjannin** [NextINpact/nextinpactv7#22]
Une photo pour montrer le soucis
![CAED4282-3BEF-45DC-9621-92C79E6F2EC0](https://user-images.githubusercontent.com/6310356/88384660-17c45300-cdad-11ea-9e5f-170989103c3e.jpeg)

**Comment by papci** [comment]
Bonjour,

Merci de lire le passage concernant Safari dans l'actualité (https://www.nextinpact.com/blog/109183-testez-next-inpact-v7.htm)
