### ISSUE TITLE
Problème de rafraichissement

### ISSUE THREAD

**Issue by francois-dorin** [NextINpact/nextinpactv7#224]
J'ai eu un problème de rafraichissement de page, où suite au clic sur un article, j'ai le titre de l'article et l'image en en-tête qui a changé, mais le contenu de l'article, le sommaire et les commentaires étaient ceux de l'article précédent. 

J'ai réalisé une capture d'écran pour montrer le problème.

Voici la démarche que j'ai suivi pour avoir le bug :
- aller sur l'article suivant : https://www.nextinpact.com/article/48372/pornodown-president-csa-nouveau-gendarme-sites-pornos
- au niveau de la colonne à droite, cliquer sur l'icône commentaires de l'article suivant : https://www.nextinpact.com/article/48269/windows-11-esthetique-nexcuse-pas-tout#comment/1905975

La première fois que j'ai fais la manipulation, j'ai également commenté l'article sur le CSA. Mais j'ai pu reproduire le bug sans commenter donc pas sur que cela soit nécessaire.

Un visuel du bug, où on voit que le titre de la page n'est pas en adéquation avec le contenu.

![bug next inpact](https://user-images.githubusercontent.com/36440144/136563338-c971df85-d6f0-4df9-ba92-210c1efe8053.png)
.

Pour information, je suis sous Chrome sous Windows 10.

**Comment by pehadavid** [comment]
merci, c'est corrigé ;)
