### ISSUE TITLE
impossible de payer par Paypal pour abonnement 1 mois à 5 euros

### ISSUE THREAD

**Issue by amel859** [NextINpact/nextinpactv7#225]
Bonjour,

Je tenais à vous signaler que,le 10/10/2021, j'ai essayer de prendre un abonnement d'un mois sur nextimpact de 5 euros, seulement l'option de payement par Paypall n'est pas disponible alors que celui de 48h est disponible ainsi que ceux de 1 ans et de 2 ans.

En vous remerciant.
Cordialement.

**Comment by pehadavid** [comment]
Bonjour,

Le paiement mensuel avec PayPal n'est pas disponible pour des raisons techniques et de frais appliqués par le prestataire, c'est pourquoi vous ne pouvez pas l'utiliser pour notre offre récurrente.
