### ISSUE TITLE
lien d'edition des abonnements newsletter et brief

### ISSUE THREAD

**Issue by tranbert** [NextINpact/nextinpactv7#228]
En voulant éditer la souscription au brief par mail, je tombe sur une page d'erreur si je clique sur le lien du mail reçu pour valider l'édition : 

_Nous avons reçu une demande pour modifier vos préférences d'abonnement pour Newsletters Next INpact.
Si vous avez fait cette demande et que vous souhaitez modifier vos préférences, utilisez le lien ci-dessous
Confirmer la mise à jour vos préférences
Si vous n'avez pas fait cette demande, elle a probablement été envoyée par quelqu'un d'autre par erreur. Vous pouvez ignorer cet e-mail, et aucun changement ne sera apporté à vos préférences d'abonnement._

page d'arrivée : 
https://i.imgur.com/PTIe623.png

**Comment by pehadavid** [comment]
Bonjour,

Pour tout ce qui concerne vos options de compte / abonnement il est préférable de passer par notre plateforme de support : https://www.nextinpact.com/contact
