### ISSUE TITLE
Lien vers les commentaires illisible sur mobile en thème noir

### ISSUE THREAD

**Issue by hwti** [NextINpact/nextinpactv7#23]
Le lien est affiché en gris par dessus l'image, mais sans aucun fond (contrairement au thème clair).

![Screenshot_20200724-134243~2](https://user-images.githubusercontent.com/827856/88387971-e13e0680-cdb3-11ea-8d1f-e9bdda6ec04a.png)

**Comment by papci** [comment]
Fixed
