### ISSUE TITLE
"Nos catégories"

### ISSUE THREAD

**Issue by ghost** [NextINpact/nextinpactv7#231]
Bonjour,

Le menu "nos catégories" affiche la réponse à deux commentaires.
Je ne crois pas que ce soit bon. J'utilise Safari sur un iPad
![5385D71B-B21F-40AE-902B-7D054F0E5552](https://user-images.githubusercontent.com/69631254/139867086-bac2cd1c-7c58-49da-85ca-a2635ebc9c4c.jpeg)

Bonne journée

**Comment by pehadavid** [comment]
Hello,  c'était temporaire, et le problème n'apparait plus ;)
