### ISSUE TITLE
Impossible de changer de mot de passe dans le compte

### ISSUE THREAD

**Issue by Epy** [NextINpact/nextinpactv7#234]
Bonjour 

Dans l'interface de gestion du compte, le changement de mot de passe ne fonctionne pas:
![Screenshot_2021-11-26 Votre profil](https://user-images.githubusercontent.com/450856/143577760-07aaa360-d9d5-473c-ada6-72c9aab98eaa.png)
ou peut-être est-ce à cause des caractères spéciaux ?
Le mot de passe actuel est bon et a été vérifié

**Comment by pehadavid** [comment]
Hello, 

Merci, un correctif est en cours ;)

**Comment by pehadavid** [comment]
Un correctif a été déployé et des messages d'erreurs plus explicites ont été ajouté.  Si l'erreur persiste de ton coté, je t'invite a contacter le support (https://www.nextinpact.com/contact) afin qu'on puisse regarder le compte en détail.

**Comment by Epy** [comment]
Merci !
