### ISSUE TITLE
Changement de mot de passe impossible

### ISSUE THREAD

**Issue by XdiZ** [NextINpact/nextinpactv7#236]
Bonjour,

Une fois connecté sur la page https://compte.nextinpact.com/gestion-util, j'ai voulu changer mon mot de passe, mais après avoir mis mon mot de passe actuel, un nouveau mot de passe généré par LastPass et le mot de passe confirmé, je clique sur "Valider" et j'ai l'erreur "Incorrect Password". Au début je pensais que l'extension uBlock bloquait la requête, mais après avoir désactivé uBlock et vérifier dans le devtools la request, j'ai vu que la requête partait bien (ok 200).
L'erreur n'est pas explicite, car on ne sait pas combien de caractère on a droit, on ne sait pas les différentes caractéristiques demandés à un mot de passe que vous acceptez...

Payload exemple de la requête, pas top que ça soit en clair le mot de passe...
OldPassword: toto
NewPassword: nextinpact
ConfirmPassword: nextinpact

Du coup j'ai demandé à réinitialiser mon de passe et là ça fonctionnait ;)

**Comment by pehadavid** [comment]
Bonjour,

Plusieurs mise à jour ont eu lieu et la fonctionnalité a été fixé depuis ;)

Merci.
