### ISSUE TITLE
Sommaire des articles ne se réaffiche pas après lecture des commentaires

### ISSUE THREAD

**Issue by Korhm** [NextINpact/nextinpactv7#237]
Bonjour,

lorsque je lis un article, il y a le sommaire associé qui affiche le titre du paragraphe au fur et à mesure du scroll.
Lorsque je scroll sur les commentaires, il n'est pas affiché.

Cependant, lorsque je scroll de nouveau vers le haut pour revenir à l'article, il ne se réaffiche pas.

**Comment by BenjaminINpact** [comment]
Hello,
Merci de ton retour, effectivement il y a un comportement étrange sur ce menu, nous allons investiguer.

**Comment by BenjaminINpact** [comment]
C'est corrigé ;)
