### ISSUE TITLE
Le flux RSS complet ne fonctionne plus depuis vendredi après-midi (caractères ^B)

### ISSUE THREAD

**Issue by Exagone313** [NextINpact/nextinpactv7#239]
Bonjour,

Le flux RSS renvoie du XML non valide depuis la sortie de la news [Plan quantique en France : une plateforme de calcul hybride, deux EquipEx+ et dix projets](https://www.nextinpact.com/article/68595/plan-quantique-en-france-plateforme-calcul-hybride-deux-equipex-et-dix-projets). Mon agrégateur de flux a pu récupérer l'article précédent *Emmanuel Macron contraint de retirer sa Lettre aux Français de ses comptes Twitter et Facebook* mais est en erreur depuis.

En effet, le XML reçu est invalide :

```
$ xmllint feed.xml
feed.xml:35: parser error : CData section not finished
<p>Un an apr&egrave;s l&rsquo;annonce d&rsquo;Emma
uantique, telle que la Plateforme nationale de calcul quantique hybride HQI (HPC
                                                                               ^
feed.xml:35: parser error : PCDATA invalid Char value 2
uantique, telle que la Plateforme nationale de calcul quantique hybride HQI (HPC
                                                                               ^
feed.xml:35: parser error : Opening and ending tag mismatch: description line 26 and em
ateforme nationale de calcul quantique hybride HQI (HPCQuantum Initiative)</em>
                                                                               ^
feed.xml:35: parser error : Opening and ending tag mismatch: item line 18 and p
un budget de 70 millions d’euros pour un objectif de 170 millions au total.</p
                                                                               ^
feed.xml:51: parser error : PCDATA invalid Char value 2
une multitude d’approches, pour faire passer la cryptographie à l’ère post
                                                                               ^
feed.xml:60: parser error : Sequence ']]>' not allowed in content
 les communications, la santé, la sécurité et les sciences fondamentales.</p>
                                                                               ^
feed.xml:60: parser error : Opening and ending tag mismatch: channel line 1 and description
ons, la santé, la sécurité et les sciences fondamentales.</p>]]></description
                                                                               ^
feed.xml:61: parser error : Opening and ending tag mismatch: rss line 1 and item
                </item> <item>
                       ^
feed.xml:61: parser error : Extra content at the end of the document
                </item> <item>
                        ^
```

En regardant le flux dans un éditeur, on constate que l'article contient des caractères `^B` (`0x02` en ASCII), il s'agit probablement d'une erreur.

En solution à court terme, il faudrait retirer ces caractères de l'article concerné.

En solution à long terme, il faudrait améliorer la gestion des caractères non-imprimables.

**Comment by Exagone313** [comment]
Le flux fonctionne de nouveau (les caractères ont été supprimés).

**Comment by Exagone313** [comment]
Le problème est survenu de nouveau sur cet article : https://www.nextinpact.com/article/68614/deploiement-fibre-larcep-compte-points-lavicca-demande-sanctions

**Comment by pehadavid** [comment]
> Le problème est survenu de nouveau sur cet article : https://www.nextinpact.com/article/68614/deploiement-fibre-larcep-compte-points-lavicca-demande-sanctions

c'est corrigé et un patch pour éviter de futurs problèmes du même type va être déployé  cette semaine.

**Comment by Exagone313** [comment]
Super merci !

**Comment by francois-dorin** [comment]
Je ne sais pas si c'est lié, mais mon flux RSS ne fonctionne plus du tout. Erreur 404 !
J'ai vérifié les liens directement depuis la partie abonné quand on est logué.

**Comment by Exagone313** [comment]
@francois-dorin, ce n'est pas lié, voir mon commentaire dans #240 (qui pour moi est une issue à rouvrir)

**Comment by francois-dorin** [comment]
@Exagone313 Effectivement. La prochaine fois, je regarderai aussi dans les issues fermées pour voir s'il y a quelque chose de plus approchant !

L'issue #240 a été marquée comme doublon mais ce n'est pas le cas. Elle est donc aussi à rouvrir pour moi.

**Comment by pehadavid** [comment]
@Exagone313 @francois-dorin en l'occurence, c'était bien un duplicate car le flux RSS a été brièvement retiré pour appliquer un patch pour traiter le souci de ce ticket.

Le souci de 404 que vous évoquez est un peu différent car il ne se produit que dans le cas ou vous tentez de le consulter via votre navigateur, le flux étant fonctionnel dans un aggregateur (ou via curl). Ceci étant dit, on sait que ça pose des soucis de compréhension et on va donc restaurer sa consultation via un browser.

**Comment by pehadavid** [comment]
le tout étant fixé et en prod ;)
