### ISSUE TITLE
Mode incognito : Aide et Inpact-Hardware

### ISSUE THREAD

**Issue by Zuhlf** [NextINpact/nextinpactv7#24]
Bonjour,
J'ai testé le mode incognito j'ai vu deux soucis : 
- L'aide n'est pas complétée : Lorem ipsum dolor sit amet n'aide pas trop ! ;)
- En mode incognito  les articles Inpact-Hardware dans le flux des articles renvoient sur le site Inpact-Hardware version normale et non une version incognito. Est-il possible de fixer cela ?

**Comment by papci** [comment]
Pour le premier point, c'est corrigé ;)
En ce qui concerne INpact Hardware, ce dernier comportera un mode incognito dédiée.
