### ISSUE TITLE
Bouton slick invisible

### ISSUE THREAD

**Issue by darkweizer** [NextINpact/nextinpactv7#241]
Bonjour,

Ce n'est pas la première fois que ça m'arrive et donc je me décide à enfin ouvrir un ticket ^^.
Les boutons avant et après des carrousels ne sont pas visibles si l'image derrière est de la même couleur.
Blanc pour les thèmes sombres comme [ici](https://ibb.co/1LxKgNP) ou [là](https://ibb.co/5c6kh8H). Mais pratiquement tout les boutons des dessins de Floc de [cette semaines](https://www.nextinpact.com/article/68670/flock-aussi-est-largement-imprevisible) sont invisibles.
Je n'ai pas trouvé d'image avec le même fond que les boutons en thème clair mais le souci doit aussi y être présent.

Serait-il possible d'ajouter un border (noir pour les thèmes sombres et blanc pour les thèmes clairs), un shadow, ou que sais-je ^^,  aux boutons, histoire de toujours pouvoir les voir ?

Cordialement.

**Comment by pehadavid** [comment]
C'est corrigé, merci pour ta patience :)

**Comment by darkweizer** [comment]
Génial 👌🏻. Mercii
