### ISSUE TITLE
Erreur de lien en mail de retour de correction d'erreur/typo

### ISSUE THREAD

**Issue by DanLo-peratingSystem** [NextINpact/nextinpactv7#242]
Bonjour,

Juste pour signaler que j'ai pu constater aujourd'hui une erreur dans le mail qui est envoyé de votre part en retour, quand on signale une erreur dans un article.

Dans les mails en question, à la fin du mail figure un lien vers l'article concerné, sous la forme : 
> Lien direct : [titre de l'article](https://exemple.url)

Le fait est qu'en cliquant sur ce lien aujourd'hui, je suis tombé sur ceci : 
![image](https://user-images.githubusercontent.com/11614445/161755284-c806a5cd-0490-4306-a965-3c385b24d654.png)

Article et lien que j'avais dans le mail : [Ubuntu 22.04 : sous les nouvelles couleurs, des améliorations significatives](http://)

**Comment by pehadavid** [comment]
Hello,

Merci pour l'alerte, je vais en parler avec la rédaction pour qu'ils évitent de transmettre leur lien privé.
