### ISSUE TITLE
404 navigation Dossiers/Tests/Guides/Tutoriels

### ISSUE THREAD

**Issue by darkweizer** [NextINpact/nextinpactv7#243]
Bonjour,

Quand on veut naviguer entre les pages de ces onglets, on tombe systématiquement sur des pages 404.
Exemple : [https://ibb.co/VqZCWGT](https://ibb.co/VqZCWGT)
Pas de souci pour l'onglet Actualités !
J'ai essayé de reproduire l'url comme pour les actualités, càd en ajoutant /page/2 à la fin de l'url ([https://www.nextinpact.com/t/dossiers/page/2](https://www.nextinpact.com/t/dossiers/page/2)) mais j'ai aussi une 404.

[Ma config](http://supportdetails.net/6RLD1I0B)

Cordialement.

**Comment by pehadavid** [comment]
c'est corrigé, merci à toi :)

**Comment by darkweizer** [comment]
Je confirme 👌🏻. Merci 😀
