### ISSUE TITLE
Automatiser l'insertion d'espace insécable dans les articles

### ISSUE THREAD

**Issue by DuchkPy** [NextINpact/nextinpactv7#245]
Bonjour,

Pour reprendre l'issue #14, qui était indiqué comme mis en place, mais il semble y avoir encore des ratés. Par exemple :
![image](https://user-images.githubusercontent.com/36851093/165752471-45cdb787-6e57-4b3c-8fda-b0f5a7a17a8b.png)
Venant de l'article : https://www.nextinpact.com/article/69022/identite-numerique-cnil-approuve-successeur-dalicem#comment/2069349

J'ai aussi joué avec le css `.article-content-padding`, l'augmentant et je voie que ce n'est pas un caractère isolé :
![image](https://user-images.githubusercontent.com/36851093/165753657-279d88fc-d14e-4521-ac27-d9f469e84ed6.png)

D'après ce que j'ai compris des réponses du précédent issue, c'était ajouté pour les rédacteurs, donc est-ce vraiment le cas lors de pigistes ?

**Comment by pehadavid** [comment]
Bonjour,

L'ensemble de la rédaction dispose des mêmes outils ;) 

Cependant, aucune évolution plus poussée n'est prévue pour la gestion des espaces insécables.
