### ISSUE TITLE
Connexion non persistante

### ISSUE THREAD

**Issue by Exagone313** [NextINpact/nextinpactv7#246]
Bonjour,

Depuis quelques jours, je dois me reconnecter chaque jour sur NextINpact.

Après vérification, il suffit de fermer et rouvrir le navigateur pour être déconnecté.

Je n'ai pas changé de configuration de mon côté.

Le token JWT semble valide 180 jours (exp - nbf), ça semble correct de ce côté aussi.

Configuration : Firefox 100.0.2

**Comment by pehadavid** [comment]
Bonjour,

Il semble que ce soit un problème coté Firefox et non NXi (que je ne reproduit pas sur FF 100.0 Windows et Ubuntu) à titre d'information). A voir coté paramètres de vie privée et éventuelles extensions.

**Comment by Exagone313** [comment]
En effet, il s'agit d'un bug introduit dans Cookie AutoDelete, qui supprime tout le local storage à l'ouverture.

https://github.com/Cookie-AutoDelete/Cookie-AutoDelete/issues/1395
