### ISSUE TITLE
Flux RSS en 404

### ISSUE THREAD

**Issue by aurmil** [NextINpact/nextinpactv7#247]
bonjour,
depuis environ 13h, l'URL au format https://www.nextinpact.com/rss-complet/[id]/[clé] que j'utilisais est en 404
la même URL + ".xml" (URL trouvée dans le menu du site) est en 200 mais vide

**Comment by sethangel79** [comment]
Bonjour,
Idem de mon côté avec les deux URL proposées (brief détaillé ou global) : réponse en 200 mais vide

**Comment by BenjaminINpact** [comment]
Hello, 
Merci pour votre retour, le correctif vient d'être mis en place.
