### ISSUE TITLE
Lien vers les images "enclosures" dans le flux RSS complet incorrects (404)

### ISSUE THREAD

**Issue by Exagone313** [NextINpact/nextinpactv7#248]
Bonjour,

J'ai constaté que les images "enclosures", qui accompagnent les articles (notamment le Brief) ne 'affiche plus dans le flux. En étudiant un petit peu, je constate que les liens pointent vers des fichiers vides et que le code HTTP est 404 :

```xml
<item>
                <title><![CDATA[Twitter déploie Circle, sa fonction de type « Amis proches »]]></title>
                <link>https://www.nextinpact.com/lebrief/69311/twitter-deploie-circle-sa-fonction-type-amis-proches</link>
                <guid isPermaLink="true">https://www.nextinpact.com/lebrief/69311/twitter-deploie-circle-sa-fonction-type-amis-proches</guid>
                <pubDate>Tue, 07 Jun 2022 08:07:30 +0000</pubDate>
                <creator xmlns="http://purl.org/dc/elements/1.1/"></creator>   
                <enclosure type="image/jpeg" url="https://cdnx.nextinpact.com/images/images/bd/wide-linked-media/8699.jpg" length="6400"/>
                <comments>https://www.nextinpact.com/lebrief/69311/twitter-deploie-circle-sa-fonction-type-amis-proches#/page/1</comments>
                <description><![CDATA[<p>(...)</p> ]]></description>
                </item>
```
```
$ curl -I https://cdnx.nextinpact.com/images/images/bd/wide-linked-media/8699.jpg
HTTP/2 404 
date: Wed, 08 Jun 2022 07:59:01 GMT
content-length: 0
...
```

Le résultat est le même pour des anciens articles dont les images s'affichaient auparavant. Je suppose à une modification du code de génération du flux ou à une suppression des fichiers involontaire (les images redimensionnées qui s'affichent sur les pages web ne sont pas affectées).

**Comment by BenjaminINpact** [comment]
Hello, 
Merci pour ton retour, effectivement, il y a un bug sur la génération de l'url de l'image. Je vais checker

**Comment by BenjaminINpact** [comment]
C'est corrigé, selon les aggrégateurs et leur système de cache, il peut y avoir un délai de mise à jour.
