### ISSUE TITLE
Impossible d'ajouter un nouvel avatar

### ISSUE THREAD

**Issue by lphaweb** [NextINpact/nextinpactv7#253]
Bonjour :)

Nouveau abonné, nouveau compte, il m'est impossible d'ajouter un nouvel avatar à partir de la page compte, onglet profil (https://compte.nextinpact.com/gestion-util) 

L'avatar semble s'uploader mais lorsque je refresh la page pour vérifier, l'avatar n'apparaît pas (en fouillant le code source, le lien de l'avatar est cassé [erreur 404])

**Comment by BenjaminINpact** [comment]
Hello, 
Si le problème est encore d'actualité, il s'agit d'un souci lié au compte, il faudrait contacter directement le support via https://www.nextinpact.com/contact en précisant le mail utilisé pour votre compte.
