### ISSUE TITLE
Affichage du sommaire caché

### ISSUE THREAD

**Issue by mickaelperrier** [NextINpact/nextinpactv7#255]
Bonjour,

Aujourd'hui sur mon navigateur, le sommaire des articles est « caché » dans la petite barre de scroll en haut à gauche. Le curseur orange descend bien, et s'adapte à la hauteur des titres, mais les titres eux-mêmes ne sont plus visibles. Je peux les afficher en passant le curseur (hover) sur la barre de scroll, ce qui fait apparaître le sommaire par-dessus le contenu de l'article. Et il disparait quand j'enlève mon curseur.
C'est tellement smooth qu'on dirait une « fonctionnalité », mais ça enlève tout l'intérêt d'un sommaire, et le curseur orange ne sert plus à rien, puisque sa hauteur variable n'indique rien de pertinent. Et l'affichage par la droite masque l'article, alors que j'ai un espace vide sur la gauche.

Is it a bug or a feature ?

Firefox 103.0.1

![Capture d’écran 2022-08-04 201816](https://user-images.githubusercontent.com/2479041/182924688-aeee9639-73fb-4245-af76-f69fa8646eae.png)

**Comment by BenjaminINpact** [comment]
Hello, 
Cela a toujours été comme ça, en tout cas depuis que ce menu existe sur la V7, donc c'est une feature mais pas nouvelle ^^.  Cela dépend de la largeur de l'écran, sur des écrans plus larges, ce menu est toujours affiché.

**Comment by BenjaminINpact** [comment]
.

**Comment by mickaelperrier** [comment]
En effet, j'ai légèrement changé ma configuration d'écran récemment, et je découvre le mode _compact/caché_ du sommaire 😅

Je ne le trouve pas très pratique, mais je ne vois comment faire mieux quand la place manque. Y accéder via un bouton qui resterait en haut à gauche (plus visible que la barre actuelle), et qui ferait apparaître le même sommaire plus en gauche en limitant la superposition avec l'article, peut-être ?

De mon coté j'ai affiné le niveau de zoom navigateur par défaut pour NXI afin d'y afficher le sommaire _étendu_, que je trouve vraiment plus pratique.

Bref, désolé pour le dérangement !

**Comment by BenjaminINpact** [comment]
Pas de soucis ! Je cloture le ticket ;)
