### ISSUE TITLE
Abonnement : bug sur la page lors d'un ré-abonnement

### ISSUE THREAD

**Issue by Freeben666** [NextINpact/nextinpactv7#256]
Bonjour,

Mon abonnement vient tout juste d'expirer, et j'ai donc souhaité me réabonner. Petit problème, la page https://compte.nextinpact.com/gestion/abonnement a l'air buguée:
![image](https://user-images.githubusercontent.com/25664142/186609426-f3c0e31e-afd3-460f-8d49-77a76198698a.png)

Mon compte NxI : Freeben666

**Comment by BenjaminINpact** [comment]
Hello, 
J'ai répondu via le support ;)

**Comment by Freeben666** [comment]
Malheureusement, le problème persiste :-/

**Comment by Freeben666** [comment]
Malheureusement le problème persiste

**Comment by Freeben666** [comment]
Je ne sais pas ce qui a été changé, mais j'ai pu me réabonner ! Merci :-)
