### ISSUE TITLE
Offrir un abonnenement : `Payer NaN € par CB`

### ISSUE THREAD

**Issue by Nightmaster** [NextINpact/nextinpactv7#260]
Il semblerait le contenu du bouton de paiement utilise `parseInt` ou `parseFloat` sur un élément inexistant/incorrect, et que le cas ne soit pas géré (résultat étant `NaN`), et que résultat de la fonction de parsing soit injecté tel quel dans le texte du bouton.
Un simple bout de code type celui ci-dessous devrait régler le problème 😉 
```javascript
const amount = parseFloat(element.value, 10);
button.querySelector('.txt-btn').innerText = `Payer ${ isNan(amount) ? 0 : amount }€ par CB`;
```

URL où le souci se produit : https://compte.nextinpact.com/offrir-abonnement
Exemple en image : ![image](https://user-images.githubusercontent.com/4302581/208994194-08f93aef-f236-4342-b7a0-c97447d6548e.png)
Testé sur Firefox 108.0.1, tous add-ons désactivés, avec/sans navigation privée et protection native (dés)activée

**Comment by BenjaminINpact** [comment]
Merci pour ton retour, je vais corriger ça.

**Comment by BenjaminINpact** [comment]
C'est corrigé :)
