### ISSUE TITLE
Filtrer les articles lus

### ISSUE THREAD

**Issue by bandinoo** [NextINpact/nextinpactv7#261]
Bonjour.
Serait-il possible d'associer un bouton ou une case à cocher "article lu" à chaque news et de pouvoir les filtrer de manière à n'afficher que les articles non lus ? 
Bonne journée.

**Comment by BenjaminINpact** [comment]
Hello Bandinoo,
Alors ce n'est pas prévu pour le moment mais cela mérite d'être réfléchi.
Bonne journée ;)
