### ISSUE TITLE
Problème de certificat

### ISSUE THREAD

**Issue by arobase-che** [NextINpact/nextinpactv7#268]
Bonjour,

L'accès à NextInpact m'est parfois impossible. Je rencontre un problème de certificat.
Le certificat qui m'est proposé est auto-signé et à destination de (ou se fait passé pour) « ingress.local ». 

« Kubernetes Ingress Controller Fake Certificate » c'est donc soit un problème de configuration soit un acteur malveillant qui se fait passé pour un problème de configuration.

Je vous transmet le certificat.

```
-----BEGIN CERTIFICATE-----
MIIDbzCCAlegAwIBAgIQFh85WFV3E1VvTO1Co3WsoDANBgkqhkiG9w0BAQsFADBL
MRAwDgYDVQQKEwdBY21lIENvMTcwNQYDVQQDEy5LdWJlcm5ldGVzIEluZ3Jlc3Mg
Q29udHJvbGxlciBGYWtlIENlcnRpZmljYXRlMB4XDTIzMDgwMjExMzQ0MloXDTI0
MDgwMTExMzQ0MlowSzEQMA4GA1UEChMHQWNtZSBDbzE3MDUGA1UEAxMuS3ViZXJu
ZXRlcyBJbmdyZXNzIENvbnRyb2xsZXIgRmFrZSBDZXJ0aWZpY2F0ZTCCASIwDQYJ
KoZIhvcNAQEBBQADggEPADCCAQoCggEBAMT/0GWhQjQG/5jUXebGph8aQhZ3s7RU
unnuml1Z0XaJZNHpjDgWFEh4FvTgevYlZ7aTPN+rcBhGWbLwrscxrvux29inFcCv
GyvBY0TeRG+s6XwCeR4Z2HpyI9MinhjD0+FJiuxcR5rw97daq7FDt9HLidOwRIXN
74cNSv0Vng6yZtefcNGLNkXL1R7071IDbQlHs6QvKI0dkNysFS+Ly0Shj/URwfH2
69FaUDME10dlmZq5ZVkAd/eZo5Hb7D75f6/U6AfHEwM6JwL0i264rKgpDnAq0Ybi
D7JGg45BINyGdL8QZJ3zGZcSipw+kONzaPpfYJB1YFysZ2pHv33x1AsCAwEAAaNP
ME0wDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB
/wQCMAAwGAYDVR0RBBEwD4INaW5ncmVzcy5sb2NhbDANBgkqhkiG9w0BAQsFAAOC
AQEAuYOxh/YHMamptvkF2QGYKq7ciNv18mgouFQAVw/M8zJbU2Rh587H081qCzac
jpDjiOxoh/va6X4/N4tIo2uF+rN8hSgo9MqojdZ2WH9d2UBPvCVCUgVzvCSeCaC+
0rOiFxWtofsHT8q1o4yfCOeEZi/+pIWhr20M7837vQYvtuproCVYsEPM6M7WttJD
MRh2xQMIC2cl34ToHTlJuceHs+hCPHVSlKWDRM93aID7M/hrrbuuU9kO372z/9E7
tL4j5P/pfzoU0aQdXdfqAunMTN0KVHaaOcF0JB/CdxfQwE6rlrYhyaMKZ2fL4pID
SEKEuTwpKxn3bb2n/tDxCVGP2Q==
-----END CERTIFICATE-----
```

Je rencontre le problème sur plusieurs connections mais aléatoirement le problème disparaît. 

Edit: L'impact d'accepter le certificat est très limité donc je pense plus à un problème de configuration.

**Comment by lapoigne** [comment]
J'avais le soucis sur une de mes machines, c'était le DOH Cloudfare qui merdait.

**Comment by arobase-che** [comment]
Intéressant. À voir si c'est lié vraiment. Je pense que je dois effectivement avoir le DoH activé.

Pour l'instant je penche encore pour un problème coté nextinpact mais je check.
J'ai le DoT activé en global sur mon système et DoH utilisé par Firefox mais j'utilise NextDNS (et non Cloudfare par défaut). En changeant, je ne semble pas avoir particulièrement plus le problème.

En tout cas, je n'arrive pas à reproduire immédiatement.
