### ISSUE TITLE
"Unhandled Navigation Error:"

### ISSUE THREAD

**Issue by Passific** [NextINpact/nextinpactv7#29]
Contexte:
- Windows 10, Version 1903 (OS Build 18362.959)
- Firefox 79.0 (64-bit)

![image](https://user-images.githubusercontent.com/2100205/89160834-fc5a0480-d571-11ea-92e4-d0aa316b428d.png)

Après avoir mis un point d'arrêt :
![image](https://user-images.githubusercontent.com/2100205/89161180-8e620d00-d572-11ea-86a0-eb005c89a35c.png)

**Comment by Passific** [comment]
Pour info, après avoir désinscrit **manuellement** le SW le problème semble ne plus être présent.
Du coup je n'ai pas eu trop l'occasion de tester cette V7, parce que jusqu'à présent j'avais une page noire...

**Comment by papci** [comment]
Je ferme car il s'agissait d'un probleme inhérent a l'envionnement Beta
