### ISSUE TITLE
Le commentaire ne charge pas au survol sur le nom de l'utilisateur

### ISSUE THREAD

**Issue by Andrufus** [NextINpact/nextinpactv7#3]
Ce sera surement plus clair avec une image : 
![image](https://user-images.githubusercontent.com/5487403/88176582-ca6aa900-cc27-11ea-9639-9ba4f252b2a2.png)

La requête effectuée est `https://api-v1-beta.nextinpact.com/api/v1/Commentaire/get/undefined`
Et la réponse :
```json
{
"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1",
"title":"One or more validation errors occurred.",
"status":400,
"traceId":"|64aca0b0-4e06dcb0d8753b8c.",
"errors":{"id":["The value 'undefined' is not valid."]}
}
```

**Comment by papci** [comment]
Fixed

**Comment by bansan85** [comment]
@papci Est-ce que les modifications ont été poussées ?

J'ai essayé et j'ai :

![ChargementCommentaireEchec](https://user-images.githubusercontent.com/9248729/89274133-cb94d080-d640-11ea-8bc0-a172ffc0292c.png)

**Comment by papci** [comment]
Oui, essaye en navigation privée, parfois la mise à jour ne se déclenche pas à cause de la protection d'accès à la Beta.

**Comment by bansan85** [comment]
> Oui, essaye en navigation privée, parfois la mise à jour ne se déclenche pas à cause de la protection d'accès à la Beta.

Merci, c'est bon :)
