### ISSUE TITLE
Le sommaire volant ne correspond pas à celui de l'article

### ISSUE THREAD

**Issue by bansan85** [NextINpact/nextinpactv7#33]
Avec la page https://beta7.nextinpact.com/article/23177/109205-hadopi-82-millions-deuros-subventions-publiques-87000-euros-damendes j'ai le sommaire volant suivant :

![image](https://user-images.githubusercontent.com/9248729/89291364-b167ec00-d65a-11ea-831b-cc7c2153e5ce.png)

Si j'ai bien compris, l'introduction désigne le texte avant le premier titre de paragraphe. C'est ça ?

Quand je fais défiler, le premier titre dans l'article est "Les IP partagées entre plusieurs abonnés, caillou de la Hadopi". Ce titre est manquant dans le sommaire volant.
Idem pour le titre "Somme totale des amendes « Hadopi » ? 87 000 euros".

Est-ce normal ? Ce qui fait qu'à chaque titre rencontré dans la page, le sommaire passe au suivant. Et donc, quand on arrive au dernier paragraphe, le sommaire ne m'affiche plus le paragraphe en cours :

![image](https://user-images.githubusercontent.com/9248729/89291738-5c78a580-d65b-11ea-89e7-ff7f4788bcfc.png)

Petite question bonus : est-ce normal que "Introduction" garde sa barre verticale orange ?

**Comment by BenjaminINpact** [comment]
Merci de tes retours Bansan ! c'est corrigé.
