### ISSUE TITLE
Sommaire volant : une colonne du trait vertical orange fait le yoyo

### ISSUE THREAD

**Issue by bansan85** [NextINpact/nextinpactv7#39]
J'ai hésité à vous l'envoyer car c'est un bug vraiment mineur mais depuis, je ne vois plus que ça.

La dernière colonne du trait vertical orange dans le sommaire vertical ne suit pas le trait vertical orange principal.

https://beta7.nextinpact.com/article/27175/109211-les-flux-encore-partiels-25-copie-privee-pour-2019

![image](https://user-images.githubusercontent.com/9248729/89527575-d50d6c80-d7e9-11ea-9f37-068e5c2b6a84.png)

ou encore

![image](https://user-images.githubusercontent.com/9248729/89527646-f79f8580-d7e9-11ea-94c1-63bfde79514b.png)

Bonne continuation ❤️ , je ne vois presque plus de bug.

**Comment by papci** [comment]
Fixé en parti ;) pour la légère bordure résiduelle, il semble plutôt que ce soit un bug du moteur de rendu.

**Comment by bansan85** [comment]
@papci : effectivement, ça semblait un bug du moteur de rendu. Depuis la version de Chrome 86, plus de problème.
