### ISSUE TITLE
Les liens de titre markdown ne fonctionnent pas

### ISSUE THREAD

**Issue by raf64flo** [NextINpact/nextinpactv7#4]
Bonjour,

Bug ou pas, les liens dans les titres de commentaire en markdown ne fonctionnent pas.

Exemple : https://beta7.nextinpact.com/article/4261/13115-pour-jean-castex----les-reseaux-sociaux-c-est-le-regime-de-vichy--#comment/312188

Avec ce commentaire en markdown par exemple : 

```markdown
# Serait-ce du _markdown_ ?!

Alors ?

## Mais oui, c&#39;est bien du __markdown__ !

Du coup, les [liens de titre](#heading-link) devraient fonctionner ?

### Un lien {#heading-link}

Ci-dessus gît un lien cassé... :-/

## Un bon titre

Court et concis comme on les aime.
```

L'attendu serait ce qui suit : 

----

# Serait-ce du _markdown_ ?!

Alors ?

## Mais oui, c&#39;est bien du __markdown__ !

Du coup, les [liens de titre](#heading-link) devraient fonctionner ?

### Un lien {#heading-link}

Ci-dessus gît un lien cassé... :-/

## Un bon titre

Court et concis comme on les aime.

----

Bon apparemment, c'est pas mieux sur Github...

**Comment by raf64flo** [comment]
Note, à toutes fins utiles, voici le rapport demandé : http://supportdetails.net/XZ2SGDDA

**Comment by papci** [comment]
Bonjour,

On ne prends pas en charge l'ensemble de Markdown, seulement ce qui est nécessaire à la rédaction d'un commentaire ;)
