### ISSUE TITLE
#LeBref : l'URL lebrief/1 désigne le dernier #LeBref et non pas le premier

### ISSUE THREAD

**Issue by bansan85** [NextINpact/nextinpactv7#40]
#LeBref du dernier jour est à l'URL https://beta7.nextinpact.com/lebrief/1
Celui du jour d'avant https://beta7.nextinpact.com/lebrief/2

Est-ce un choix judicieux ?

Cela veut dire qu'à chaque ajout d'un #LeBref, le contenu de la page va changer pour les indexeurs de contenu (Google & co). Vous risquez d'augmenter votre bande passante et eux de ne pas s'y retrouver.

**Comment by papci** [comment]
C'est simplement du à l'état de la beta et à nos besoins interne, ça ne sera pas le cas en Release.
