### ISSUE TITLE
#LeBref : les dates suivantes et précédentes sont parfois manquantes

### ISSUE THREAD

**Issue by bansan85** [NextINpact/nextinpactv7#41]
En testant de naviguer via l'URL dans les différents #LeBref, j'ai parfois les dates suivantes et précédentes sont manquantes.

![image](https://user-images.githubusercontent.com/9248729/89528506-73e69880-d7eb-11ea-9f24-2f1c529316a3.png)

**Comment by papci** [comment]
J'ai édité pour des raisons de sécurité pour ton compte ;)

**Comment by bansan85** [comment]
> 
> 
> J'ai édité pour des raisons de sécurité pour ton compte ;)

Merci 😃 ❤️  J'avoue que je m'étais posé la question au moment d'envoyer le log mais j'ai pas réfléchis plus que ça... J'ai supprimé l'historique du message aussi.
