### ISSUE TITLE
Citations dans les commentaires

### ISSUE THREAD

**Issue by Passific** [NextINpact/nextinpactv7#42]
Les citations ne sont pas correctement affichés dans les commentaires :
![image](https://user-images.githubusercontent.com/2100205/89541603-e44ae500-d7fe-11ea-9139-9b5e0461e7ed.png)
Original :
![image](https://user-images.githubusercontent.com/2100205/89541736-093f5800-d7ff-11ea-9fac-7ef7aa59e7ab.png)

Une question d'ailleurs : est-ce que la màj de la BDD de la beta se fait manuellement ? Parce qu'il manque des commentaires et des articles. Du coup si je fais un commentaire sur la beta sera-t-il visible sur la "release" ?

**Comment by bansan85** [comment]
Oui, la base de données de la bêta est remplacée à minuit par celle de NextInpact. Tu peux donc faire n'importe quoi avec les commentaires de la Beta.

**Comment by papci** [comment]
Comme souligné par @bansan85 (et comme dit la news associée à l'annonce :p) tout est temporaire.

**Comment by Passific** [comment]
D'accord pour la question, mais il y a quand même toujours le problème d'affichage !?
