### ISSUE TITLE
#LeBrief à un pépin

### ISSUE THREAD

**Issue by Passific** [NextINpact/nextinpactv7#43]
Impossible d'afficher #LeBrief en mode incognito...

Les "articles" de #LeBrief sont bien affiché dans la liste mais redirige vers la version non-incognito.

D'ailleurs, si vous pouviez rediriger vers la version incognito quand vous citez un autre article (dans un article, pas seulement dans #LeBrief), ça serait TOP ! (c'est déjà un probleme dans la version courante)

**Comment by BenjaminINpact** [comment]
Merci des retours Passific, c'est en voie d'être corriger.
