### ISSUE TITLE
Le thème est appliqué très tardivement

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/nextinpactv7#47]
Lorsque l'on charge ou recharge une page, le thème par défaut est visible tant que le xhr pour récupérer les options de l'utilisateur.  
Ce qui fait que quand on a un thème sombre, pendant plusieurs secondes, on a un flash blanc qui éblouit.  
Y'a évidemment le même problème sur IH. C'est vraiment pénible quand tout l'environnement de travail est sombre…

**Comment by darkweizer** [comment]
C'est surement le même souci que j'ai décrit [dans mon ticket](https://github.com/NextINpact/nextinpactv7/issues/21) 🙂

**Comment by Cqoicebordel** [comment]
Oui et non :)  
La cause est globalement la même, mais la manière de résoudre ces problèmes peut être différente. Un cookie peut être mis pour le theme, mais pas pour connaître le nombre de notifications, par exemple. 

Mais dans tous les cas, oui, j'avais raté ton bug ;)

**Comment by papci** [comment]
voir #21
