### ISSUE TITLE
Flux RSS complet en 404

### ISSUE THREAD

**Issue by gileri** [NextINpact/nextinpactv7#49]
Le flux RSS complet répond HTTP 404, quelque soit le navigateur. Je suis bien abonné pendant encore quelques mois.

https://www.nextinpact.com/rss-complet/utilisateur/clé

La regénération de clé a l'air de fonctionner, mais toujours 404 pour l'URL du flux.

EDIT : Il y a pas eu d'article entre le 2020-08-07 et 2020-08-10, je ne sais pas depuis quand c'est en 404.

**Comment by Albirew** [comment]
erreur aussi pour les flux des bon plans et lebrief

**Comment by Albirew** [comment]
erreur aussi pour les flux des bon plans et lebrief

**Comment by Cqoicebordel** [comment]
Attention, il me semble que l'URL est en 404 quand tu n'utilises pas un lecteur RSS (genre, ouvrir le lien dans le navigateur).  
Ce qui n'empêche que j'ai le même problème aussi, testé sur Akregator, Opera 12, et Thunderbird, sans succès.

**Comment by gileri** [comment]
Pas compris ta remarque @Cqoicebordel. Même comportement avec le navigateur web qu'un aggrégateur, ou cURL. 

Log tt-rss :
```
[14:42:58/1523574] start
[14:42:58/1523574] running HOOK_FETCH_FEED handlers...
[14:42:58/1523574] feed data has not been modified by a plugin.
[14:42:58/1523574] local cache will not be used for this feed
[14:42:58/1523574] last unconditional update request: 2020-08-10 05:09:34
[14:42:58/1523574] stored last modified for conditional request: 
[14:42:58/1523574] fetching [https://www.nextinpact.com/rss-complet/utilisateur/clé] (force_refetch: )...
[14:42:58/1523574] fetch done.
[14:42:58/1523574] source last modified: 
[14:42:58/1523574] unable to fetch:  [404]
```

cURL :
```
% curl -v -o -s -H 'Accept: application/rss+xml' https://www.nextinpact.com/rss-complet/utilisateur/clé 2>&1 | grep HTTP
> GET /rss-complet/utilisateur/clé HTTP/2
< HTTP/2 404 
```

À noter que le [flux RSS principal](https://www.nextinpact.com/rss/news.xml) fonctionne correctement partout.

**Comment by Cqoicebordel** [comment]
Aux dernières nouvelles, ils autorisaient seulement les agrégateurs. Si on prenait l'URL dans le navigateur, on obtenait une erreur 404 dans tous les cas.  
Tu peux essayer sur IH, utiliser l'URL de flux dans le navigateur et t'as un 404.

Tout ça pour dire, il ne faut pas tester *que* dans le navigateur. Il faut tester dans un agrégateur aussi (et tu l'as fait, donc c'est très bien :) )

**Comment by papci** [comment]
un correctif va être déployer demain dans la journée, merci de votre patience :)

**Comment by papci** [comment]
c'est corrigé.

**Comment by gileri** [comment]
Bonjour, je confirme merci !
