### ISSUE TITLE
Réactiver le threading dans les commentaires

### ISSUE THREAD

**Issue by MightyCreak** [NextINpact/nextinpactv7#5]
Bonjour!

Dans la v6 j'ai activé le threading dans les commentaires. Je trouve cette fonctionnalité incroyablement pratique. Elle permet de ne pas avoir à aller à la chasse aux réponses dans les pages de commentaires suivantes.

J'aime particulièrement le fait que le thread est limité à un seul niveau de hiérarchie, permettant d'éviter des amoncellement d'indentations, ainsi que des discussions dans les discussions.

**Comment by papci** [comment]
Bonjour,
Le mode Thread ne reviendra pas dans la v7, la fonction n'étant quasi pas utilisée sur NextV6 et nos ressources limitées.

**Comment by MightyCreak** [comment]
Je comprends.. je pense tout de même que si elle n'était pas utilisée c'est parce qu'elle était difficile à trouver et que le mix entre les deux modes pouvait créer des confusions.

**Comment by Passific** [comment]
Dommage, je plussoie pour cette fonctionnalité. Dans la V8 ? 😉
