### ISSUE TITLE
"tooltip" commentaire répondu persistant.

### ISSUE THREAD

**Issue by Mystell** [NextINpact/nextinpactv7#51]
En passant rapidement le curseur sur le "bouton" permettant de visualiser le commentaire auquel on répond le tooltip va s'afficher mais ne pas disparaitre. On doit revenir sur le bouton avant de le quitter calmement pour que le tooltip disparaisse.

**Comment by papci** [comment]
On a baissé la sensibilité pour eviter des triggers dans tout les sens, ça
