### ISSUE TITLE
Twitter contacté, avec l'option "boutons sociaux" désactivé

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/nextinpactv7#54]
En ouvrant un article, n'importe lequel, et lorsque l'on a désactivé les boutons sociaux, Kimetrack continue à montrer que Twitter a été contacté.
![image](https://user-images.githubusercontent.com/2286246/89800842-994b0d80-db2f-11ea-8af0-7dc9adc200f3.png)

Je ne sais pas si Twitter est utilisé pour d'autres fonctionnalités, mais en désactivant les boutons sociaux, je m'attendais à ce que le site n'ait aucun contact avec Twitter, FB et les autres.

**Comment by papci** [comment]
ce n'est pas du aux boutons "sociaux" mais aux intégration de tweets dans les actus ;)

**Comment by Cqoicebordel** [comment]
@papci, dans l'article https://www.nextinpact.com/blog/43360/next-inpact-v7-est-la-ce-qui-change-des-aujourdhui#comment/1820162, il ne semble pas y avoir de tweets intégrés, pourtant, Twitter est bien contacté.  
D'un point de vue tracking, c'est pas idéal.
