### ISSUE TITLE
La table des matières ne se met pas à jour lorsque "Home" est pressé

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/nextinpactv7#55]
1. Ouvrir https://www.nextinpact.com/article/43361/un-detour-par-ceinture-dasteroides-et-lacunes-kirkwood
2. Aller en bas de page. Scroller un peu vers le haut, pour que la table des matières se mette à jour
3. Presser "Home" ("Début").
⇒ La table des matières reste sur le dernier élément de la liste

![image](https://user-images.githubusercontent.com/2286246/89801771-e7144580-db30-11ea-81fe-50be59eb0a53.png)

**Comment by bastien-c** [comment]
fixed

**Comment by Cqoicebordel** [comment]
Maintenant, la table des matières ne se met pas à jour sur tous les articles : sur https://www.nextinpact.com/article/44357/la-quadrature-net-depose-nouveau-recours-contre-drones-policiers il se passe rien du tout en scrollant.
