### ISSUE TITLE
Enrichissement du flux RSS

### ISSUE THREAD

**Issue by LeoColomb** [NextINpact/nextinpactv7#59]
Quelques tickets avaient été ouverts avec la version 6, ils sont toujours d'actualité de coup je les remets ici ! 🙂 

- [x] Ajouter les sous-titres des articles (https://github.com/NextINpact/nxiv6/issues/25)
  > C'est de l'ordre du détail, mais le flux RSS même complet ne comporte pas les sous-titres d'article.
  > Vu l'effort remarquable avec lequel ces derniers sont réalisés, c'est quelque peu dommage ! 😄

- [x] Ajouter les images du Brief (https://github.com/NextINpact/nxiv6/issues/194)
  > Chaque article du Brief, sur le site, est accompagné d'une image. Souvent, cette image est nécessaire pour la compréhension de l'article.
  > 
  > Du coup, serait-il possible d'ajouter ces images au flux RSS, dans l'article du Brief ?

**Comment by Cqoicebordel** [comment]
Oui !!!  
Par ailleurs, une option pour avoir le Brief en plusieurs articles serait pas mal.

**Comment by DanieLoche** [comment]
J'ajouterais que je rencontre un bug sur certains agrégateurs de flux RSS (Zappier notamment) : La présence d'un saut de ligne dans le champ description d'un élément du flux casse la génération de l'aggrégateur..! C'est le cas sur les flux NXi avec le texte "Lire la suite" en fin de description, qui est séparé par un saut de ligne. 
![image](https://user-images.githubusercontent.com/11614445/89995570-ee029b80-dc89-11ea-9b5a-bf95a29063bf.png)

Je ne sais pas si c'est propre à l'usage que j'en fais ou si le souci impacte plus généralement...
Dans mon cas, je génère une requête au format Json raw data pour générer un message embedded sur Discord. 
La présence d'un saut de ligne à l'intérieur d'un élément du Json casse tout... :x 
Je n'ai jamais eu le souci avec d'autres flux RSS, qui généralement mettent le "Lire la suite" directement à la suite du texte de description, ou ne le mettent pas du tout (remplacé par de simples points de suspension).

**Comment by LeoColomb** [comment]
@DanieLoche C'est un peu hors sujet par rapport au ticket initial, je pense que ce serait mieux d'ouvrir un nouveau cas pour ce problème 🙂

**Comment by DanieLoche** [comment]
> 
> 
> @DanieLoche C'est un peu hors sujet par rapport au ticket initial, je pense que ce serait mieux d'ouvrir un nouveau cas pour ce problème 🙂

J'ai pris l'issue comme un "les trucs qui pourraient être changés/améliorés sur les flux RSS", mais effectivement c'est plus centré sur l'ajout de contenu au RSS. J'ai séparé l'issue. :)

**Comment by LeoColomb** [comment]
Je ferme avec le passage en Next, dont le RSS inclus les sous-titres.
