### ISSUE TITLE
Thème non conservé

### ISSUE THREAD

**Issue by faureloic** [NextINpact/nextinpactv7#6]
Lorsque j'ai voulu configurer l'aspect du site via le menu, mon choix de thème n'était plus conservé après avoir enlevé les boutons sociaux.
Pour reproduire:
- changer le thème
- décocher boutons sociaux
=> le thème rechange
![image](https://user-images.githubusercontent.com/17143576/88192350-b54c4500-cc3c-11ea-90e5-a3ca53b5b7b6.png)

Cela semble aussi le cas pour les autres paramètres

**Comment by faureloic** [comment]
sous Firefox (navigation privée)

**Comment by papci** [comment]
Fixed ;)
