### ISSUE TITLE
(confort) ajout séparateur jours

### ISSUE THREAD

**Issue by jonathanlermitage** [NextINpact/nextinpactv7#60]
Restaurer un marqueur (petit espace vertical par ex) mettant en valeur le changement de jour dans la vue principale.  
Aujourd'hui il faut lire les dates pour si l'on veut se focaliser sur les articles du jour.

**Comment by papci** [comment]
Nous avons fait le choix de ne pas réintroduire la séparation par date pour des questions éditoriales.

**Comment by jonathanlermitage** [comment]
Je pense qu'un séparatareur d'un ou deux pixels de hauteur ne serait pas bloquant ? Ce serait clairement un ajout de confort.
