### ISSUE TITLE
Heure de post d'article sur la page d'accueil

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/nextinpactv7#67]
Sur la page d'accueil, vous listez les articles avec leurs dates de parution. Logique.    
Mais vous utilisez une icône d'horloge. Or, vous n'affichez pas l'heure. Là, c'est pas logique.
![image](https://user-images.githubusercontent.com/2286246/90026264-5caa1e00-dcb7-11ea-985b-4f9b9568cf96.png)

Du coup, une solution serait soit de changer l'icône pour 📅 ou quelque chose de similaire ; soit d'afficher l'heure, en plus de la date (ce que je préférerais). Dans tous les cas, vous pouvez ajouter un tooltip avec la date et l'heure complète.

Oh et au passage, les articles de IH n'ont pas cette icône.  
Edit : Il semblerait que les articles gratuits non plus.

**Comment by papci** [comment]
En production depuis plusieurs semaines déjà ;)
