### ISSUE TITLE
Mise à jour automatique

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/nextinpactv7#68]
Régulièrement, que ce soit sur IH ou NI, une popup demande d'actualiser l'app.  
Est-ce ça pourrait être fait automatiquement ?

Parce que là, on ouvre NI, on attend son chargement complet, et on a la popup qui demande de recharger la page, alors que c'est ce qu'on vient de faire (je parle d'un point de vue utilisateur, pas technique). C'est très disruptif.

Une solution serait de mettre à jour les fichiers en cache automatiquement, et d'utiliser les nouveaux au prochain F5 ou ouverture d'onglet (du moins, j'imagine que c'est une solution).

Pour le debug, et pour ceux qui veulent, avoir un bouton "forcer la mise à jour" qui apparaîtrait dans le panneau de profil quand une mise à jour est disponible permettrait de résoudre tous les cas d'usages.

Oh, et afficher quelque part un numéro de version, pour le support, ça pourrait aider :)

**Comment by papci** [comment]
On a des choses en ce sens qui vont arriver afin que la pop-up soit moins intrusive ;)

**Comment by papci** [comment]
La pop-up fait parti du passé, les mises à jour étant désormais automatiquement appliquées

**Comment by Otiel** [comment]
Merci !
