### ISSUE TITLE
api.bonsplans.tech nécessaire au chargement des articles

### ISSUE THREAD

**Issue by Exagone313** [NextINpact/nextinpactv7#7]
Bonjour,

Si les requêtes vers `api.bonsplans.tech` sont bloquées par une extension du navigateur, alors les articles ne chargent pas.

Je ne pense pas que cet appel devrait être nécessaire, il doit être possible de gérer le cas d'erreur (exemple : dans le cas où bonsplans.tech est en maintenance).

**Comment by papci** [comment]
Fixed
