### ISSUE TITLE
[A11y] Même fermé, TAB parcours le menu de gauche

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/nextinpactv7#70]
Lorsqu'on presse de manière répété la touche TAB, on parcours le menu de gauche, même lorsqu'il est fermé.

On ne devrait pas pouvoir le parcourir tant qu'on ne l'ouvre pas.

PS : J'ai pleins de bugs de ce type que je peux remplir. Est-ce que, au moment où vous êtes dans le développement, ça vous intéresse que je le fasse, ou vous avez prévu une passe accessibilité, et qu'il sera plus intéressant que je le fasse après ?

**Comment by Cqoicebordel** [comment]
Et du coup ?  
Je continue à faire ces bugs, ou vous faites une passe dessus avant ?  
Parce que point de vue accessibilité, y'a des tonnes de trucs à régler, et je pense que ce serait plus efficace que vous vous atteliez à ça un moment, et seulement ensuite, je passe pour voir ce qui manque.

Pour l'accessibilité, essayer de naviguer qu'au clavier, et essayez avec un lecteur d'écran.

**Comment by papci** [comment]
En fonction du temps qu'il reste alloué au projet, on fera une passe complete dessus. Mais je peux absolument rien promettre en terme de timing et de réalisation.

**Comment by Cqoicebordel** [comment]
Ok, je prend note.
