### ISSUE TITLE
Reconnexion NextInpact/InpactHardware

### ISSUE THREAD

**Issue by smariel** [NextINpact/nextinpactv7#73]
Lorsque l'on est connecté avec son compte sur Next Inpact et que l'on clique vers un lien renvoyant vers Inpact Hardware, il serait bien d'être reconnecté automatiquement sur ce dernier.

Testé avec Safari sur iPad OS 13.6, en cliquant depuis Next Inpact sur l'article du 13/08/2020 "Windows 10 va permettre de choisir quel GPU utiliser, par application".

**Comment by papci** [comment]
Bonjour,

C'est prévu comme marqué dans l'actu d'annonce de Next INpact v7.
