### ISSUE TITLE
Les liens des commentaires ont target=blank plutôt que target=_blank

### ISSUE THREAD

**Issue by Exagone313** [NextINpact/nextinpactv7#8]
La valeur de l'attribut `target` devrait être `_blank` plutôt que `blank`.

De plus, il pourrait être souhaitable de ne pas inclure cet attribut. En effet, avec cet attribut, vous empêcher l'utilisateur de choisir s'il veut ou non ouvrir le lien dans un nouvel onglet. Voir aussi : https://css-tricks.com/use-target_blank/

**Comment by papci** [comment]
Fixed pour le "blank".
