### ISSUE TITLE
Menu réponse/citation/signalement dans les commentaires

### ISSUE THREAD

**Issue by SLwoodcutter** [NextINpact/nextinpactv7#82]
Bonjour,

Toujours sur iOS Safari, la ligne permettant de répondre / citer / signaler dans les commentaires a un comportement étrange.

![7353B8E0-16E0-4DC6-82F8-D720BAD20E1F](https://user-images.githubusercontent.com/69680729/90255318-6745ee00-de44-11ea-86b2-3770f4f47021.jpeg)

Elle s’active / se désactive simplement en touchant le message (et non pas en touchant la flèche en entête). 
Ça rend la lecture un peu gênante car elle apparaît / disparaît sur presque tous les messages. 

Mais le plus embêtant et qu’on ne peut pas faire un appuie long sur un lien mis dans les commentaires. Soit on sélectionne la ligne d’au dessus, soit la ligne d’en dessous.

**Comment by BenjaminINpact** [comment]
C'est réglé ;)
