### ISSUE TITLE
Changer message pour les Commentaires non abonné 

### ISSUE THREAD

**Issue by Refuznik** [NextINpact/nextinpactv7#84]
Lorsque l'on est pas ou plus abonné et que l'on cherche à commenter un article, le message suivant apparait :
"_Une erreur est survenue lors de l'envoi de votre commentaire. Veuillez réessayer ulterieurement._" 

Il faudrait plutôt changer le message du genre _Il n'y a que les abonné qui ont le droit de commenter cette article_. Comme on avait sur l'ancienne version.

**Comment by coudrak** [comment]
Il faudrait plutôt ne pas afficher la zone pour commenter, comme avant.
Taper un long commentaire, puis découvrir après que l'on ne peut pas l'envoyer, pas très user-friendly.
