### ISSUE TITLE
Ajout de flux RSS

### ISSUE THREAD

**Issue by NatMarchand** [NextINpact/nextinpactv7#86]
Hello,
Avec la v6, il était possible d'ajouter des flux RSS qui s'ajoutaient aux actualités NI.
Avec la v7, je ne retrouve plus cette fonctionnalité. Est elle prévue ou abandonnée ?
Merci !

**Comment by papci** [comment]
Bonjour,

La fonctionnalité est supprimée sur la v7. Bonne journée.
