### ISSUE TITLE
Rafraichissement des articles dans le flux RSS

### ISSUE THREAD

**Issue by JusticeRage** [NextINpact/nextinpactv7#88]
Bonjour,

Depuis la sortie de la v7, j'ai constaté que certains articles étaient constamment considérés comme remis à jour par mon flux RSS (par exemple, https://www.nextinpact.com/article/43366/publicites-adressees-a-television-comment-sera-recueilli-consentement qui revient plusieurs fois par jour depuis sa parution).
Pour autant, il ne me semble pas que ces articles soient modifiés, et encore moins de manière aussi régulière. Serait-il possible de corriger ceci ? Cela rend la lecture du flux de NextInpact particulièrement pénible.

**Comment by papci** [comment]
Bonjour,

Cela est certainement du au lancement de la v7 ou certains vieux articles ont été remonté dans les flux.

**Comment by JusticeRage** [comment]
Bonjour. Non, c'est un problème qui se produit toujours quotidiennement.
Depuis quelques jours par exemple, j'ai l'article sur [Mailo](https://www.nextinpact.com/article/43377/mailo-webmail-francais-riche-en-fonctions-en-manque-modernite) qui remonte sans arrêt.

**Comment by papci** [comment]
Sur quel Aggregateur ?

**Comment by JusticeRage** [comment]
Tiny Tiny RSS ! 
Tiny Tiny RSS !
