### ISSUE TITLE
bug sur affichage utilisateur

### ISSUE THREAD

**Issue by galerienv** [NextINpact/nextinpactv7#9]
Google Chrome Version 84.0.4147.89 (Build officiel) (64 bits) avec écran en résolution  2560x1440

Lorsque l'on regarde un utilisateur

![utilisateur bug](https://user-images.githubusercontent.com/10227016/88205431-0bc17f80-cc4d-11ea-9f9a-819166ab67d0.png)

Lorsque l'on se descend dans l'écran.
![utilisateur sans bug](https://user-images.githubusercontent.com/10227016/88205516-33b0e300-cc4d-11ea-97f8-026e58b8c914.png)

**Comment by papci** [comment]
Fixed
