### ISSUE TITLE
Lien vers IH pour les nouveaux commentaires

### ISSUE THREAD

**Issue by darkweizer** [NextINpact/nextinpactv7#91]
Bonjour,

Comme sur cette [photo](https://ibb.co/XFf7R2Q), il n'y a pas le numéro du premier nouveau commentaire dans le lien quand on veut appuyer sur le 14 (dans ce cas). Du coup on se retrouve sur l'article et non directement sur les nouveaux commentaires.

P.S. : aucun souci pour les articles NI, là il y a bien le numéro dans l'url. Pareil dans la page d'accueil de IH pour les articles IH 😊.

Cordialement.

**Comment by papci** [comment]
Fixed
