### ISSUE TITLE
Impossibilité de lire un article offert depuis un email

### ISSUE THREAD

**Issue by ElliotThiebaut** [NextINpact/nextinpactv7#94]
Je me suis vu offrir un article sur le site par email. Je n'ai pas de compte, mais dans l'article il y a un lien pour voir l'article offert, mais il redirige vers une page 404. Par conséquent je ne peux pas accéder à l'article offert.

**Comment by Mackelsj** [comment]
Impossible d'offrir un article. Il n'y a pas de hyperlien dans l'email. Et le lien de secours ne fonctionne pas

Par exemple, 
https://www.nextinpact.com/article/43392/jupiter-planete-geante-depourvue-surface-solide-protectrice-systeme-solaire


Email reçu:
-----------------
Bonjour xxx,

yyy (xxx@yyy.fr) pense que cet article pourrait vous intéresser et a décidé de vous l’offrir :


Voici son message :

Jupiter

Cet article vous sera accessible dans la limite de 10 lectures, et ne pourra pas être partagé plus largement.

En y accédant, vous autorisez Next INpact à vous inscrire à sa lettre d’information évènementielle qui vous tiendra au courant de nos dossiers et initiatives (concours, nouvelles fonctionnalités, etc.). Vous pourrez vous en désinscrire d’un simple clic et vos coordonnées ne seront pas divulguées à des tiers ni utilisées à d’autres fins.

Bonne lecture,

L’équipe de Next INpact


Pour soutenir Next INpact et accéder à tout notre contenu, abonnez-vous : http://www.nextinpact.com/abonnement
En cas de problème avec la lecture de cet article, utilisez le lien suivant : https://www.nextinpact.com/article/0/?gift=4993d29f-6234-482a-b4ee-79f3ad27f850

**Comment by papci** [comment]
fixed ;)

**Comment by Mackelsj** [comment]
Il n'y a plus d'email de parrainage envoyé.
Lors de la tentative d'offir l'article suivant, aucun email n'est reçu
https://www.nextinpact.com/article/43363/postmarketos-reappropriation-telephones-par-linux
