### ISSUE TITLE
#LeBrief : les titres des articles n’apparaissent pas dans le mode lecture de Firefox

### ISSUE THREAD

**Issue by Mozinet-fr** [NextINpact/nextinpactv7#95]
Dans les pages regroupant les articles quotidiens comme https://www.nextinpact.com/lebrief/615 les titres des articles n’apparaissent plus quand on passe en mode lecture de Firefox. C’est très désagréable, surtout si on utilise la lecture à haute voix de la page.

**Comment by Mozinet-fr** [comment]
Les `alt` des images apparaissent cependant, mais elles ne sont pas sélectionnables.

**Comment by Mozinet-fr** [comment]
Pour [le Brief 619 du 3 septembre](https://www.nextinpact.com/lebrief/619), un seul article apparait dans le mode lecture de Firefox.

**Comment by papci** [comment]
Bonjour,

Il faudrait plutot remonter ce souci a l'équipe de Firefox : les titres sont bien balisés en H2 de notre coté.

**Comment by Mozinet-fr** [comment]
Bonjour,
Le h2 ne fait pas partie du même élément que les éléments p, mais est niché dans plusieurs div séparés, ayant ainsi une structure similaire à des cadres de publicité nichés dans un article.
