### ISSUE TITLE
Connexion unifiée KO

### ISSUE THREAD

**Issue by Paul-Muad-Dib** [NextINpact/nextinpactv7#96]
Bonjour,

Il ne me semble pas que ce problème ait été remonté sur le GitHub : dans mon cas la connexion unifiée NXI -> INH ne fonctionne pas. 
Bien que connecté sur Next INpact, lorsque je clique sur un article présent dans le fil d'actualité, INpact Hardware s'affiche en mode déconnecté.
Le problème est le même sur Firefox v79 et v80 ainsi que Chrome v85.0.4183.83 avec dans tous les cas un navigateur vierge (aucun module complémentaire activé ni mode anti-pistage).

Bien cordialement.

**Comment by papci** [comment]
Bonjour,

On ne reproduit pas du tout, est-ce que ça ne serait pas du à l'utilisation d'une session pré-existante a la mise en place du système de cross identification ?

**Comment by Paul-Muad-Dib** [comment]
Bonjour,

Je ne pense pas, le problème est toujours d'actualité actuellement.

D'ailleurs je viens de m'apercevoir qu'un problème similaire existe lorsque je clique sur le pseudo d'un membre : bien que connecté sur NXI, si je clique sur le pseudo d'un membre ayant commenté un article par exemple, cela m'ouvre un nouvel onglet https://www.nextinpact.com/inpactien/XXXXXX et NXI me considère déconnecté.
Je me retrouve donc dans la situation où j'ai deux onglets NXI ouverts dans une même instance du navigateur, l'un où le site me considère connecté et l'autre pas !

pmd

**Comment by BenjaminINpact** [comment]
Bonjour, 
Après avoir tester avec plusieurs comptes, on ne reproduit toujours pas. Si le problème est encore d'actualité, vous pouvez passer par le support de Next : https://www.nextinpact.com/contact
