### ISSUE TITLE
Flux RSS complet supprime des articles

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/nextinpactv7#97]
Le flux RSS complet limite le nombre d'article à 20.  
Aujourd'hui, le Brief contenait 26 article, ce qui fait que 6 sont passés à la trappe.  
C'est pas idéal…

**Comment by Cqoicebordel** [comment]
Aujourd'hui, avec 45 articles, ça devrait être OK, mais il semble que la moitié des articles soient encore absent.

**Comment by BenjaminINpact** [comment]
Les flux rss ont été fix, merci de ton retour.
