### ISSUE TITLE
Flux RSS complet : ajouter une option pour Le Brief en un seul article

### ISSUE THREAD

**Issue by Cqoicebordel** [NextINpact/nextinpactv7#98]
Depuis les débuts du Brief, il est toujours apparu dans le flux RSS complet comme un seul article, contenant tous les articles du Brief.  
Aujourd'hui, ils sont apparus comme des articles séparés.

Je ne suis pas contre ça, au contraire, mais avoir l'option d'avoir qu'un seul article serait bienvenu.

**Comment by Otiel** [comment]
👍 

Je n'aime pas avoir des articles séparés pour chaque article du Brief. Cela "pollue" trop ma liste d'articles non lus et m'empêche de trier rapidement ce que je veux lire.

**Comment by fmunch** [comment]
Dans la v6 https://www.nextinpact.com/rss/nobrief.xml avait bien ce comportement, une seule entrée par jour pour LeBrief au lieu d'une par brève. Depuis la v7 ce n'est plus le cas, je viens de me rendre compte que j'ai raté tous les Briefs depuis la v7 :/
Et comme pour @Otiel je préfère ne pas me retrouver d'un coup avec 20 / 25 brèves non lues dans mon agrégateur.

**Comment by pehadavid** [comment]
Hello,

La fonctionnalité est en ligne ;)

**Comment by Otiel** [comment]
Merci ! ❤️

**Comment by Otiel** [comment]
Via le nouvel URL du flux (https://www.nextinpact.com/rss-complet/xxx/xxxxxx?reduceBrief=true), LeBrief du 01/10 est bien apparu dans mon aggrégateur (Inoreader) sous la forme d'un seul article.

Par contre, je n'ai pas eu LeBrief du 02/10 et du 05/10. Suis-je le seul ?

(L'URL de récupération du flux renvoie une 404 en ce moment, je ne peux pas vérifier si les articles sont bien dans le XML)

**Comment by seblez** [comment]
J'ai le même problème, j'ai ouvert ce ticket:
https://github.com/NextINpact/nextinpactv7/issues/138

**Comment by Otiel** [comment]
@seblez Il s'agit d'un autre problème.

Je pense avoir trouvé la raison à mon problème : #143
