### ISSUE TITLE
#LeBrief - Impossible de selectionner un brief avant Juin 2020

### ISSUE THREAD

**Issue by kittysavana** [NextINpact/nextinpactv7#99]
Impossible de sélectionner un brief avant Juin 2020. Voir capture ci-dessous.
Il est possible par contre d’accéder aux briefs en tapant directement leurs URLs.

![image](https://user-images.githubusercontent.com/70636915/91969099-e2991200-ed15-11ea-9114-be1e17333e16.png)

**Comment by papci** [comment]
Bonjour,

Il s'agit d'une limitation volontaire de notre part. Il est toujours possible de retrouver un article en particulier via la recherche.
